navit-gps/navit

ci/build.sh, circle.yml
just some tweak to get the circleCI builds going again
=> Circle.yml update

navit/navigation.c, navit/navit.c, po/de.po.in
Up to now the concatenation of turn announcements isn't implemented correctly.
Currently two announcements are only connected if the announcements are such close in a timely manner that they tend to get overlapped. In practice this hardly ever occurs.
In my view this is not the idea of concatenating turns. They shall be concatenated if the turns are close in a distance manner.
Hence, for me the criteria shall be like this:
- If two turns have a distance to each other that is less than the "level 2"-distance configured for the specific route item, (which stands for the "soon"-announcement), they shall be concatenated.
- The "soon" announcement for the second turn shall be suppressed in that case.
- Any announcement for the second turn from that concatenation down to "level 1" shall be …
=> Concatenation of announcements now working

cmake/version.cmake
Tried to cmake navit (for rpm building) from tarball created from my fork. Since this is no git repository then, but git executable is present on the machine, getting git revision fails fatal. In detail the regex detecting "R" fails if VERSION is unset.
This small fix prevents it from failing and instead resorts to invalid (0000) revision.
=> fix:build Cope with build fron non git tree but git present

navit/attr_def.h, navit/osd.c, navit/osd.h, navit/osd/core/osd_core.c
Change OSD-items-color for custom OSD-Layouts. I wanted to switch from night to daylayout with 100% transparent OSD backgrounds. This lead to the unreadable combination of white OSD on light grey day layout. Therefore I made some changes to set the foreground_color of an OSD item and replace the hardcoded graphics_fg_white. 
To set a custom foreground color, just add an foreground_color="#AAABBB" to the osd tag. It might be used with osd_configuration for the current layout. Default is white of course.
=> Enable OSD color settings for non-text-OSD

navit/osd/core/osd_core.c
Now you can nicely scale osd buttons.
This helps if using pure .svg images, as .svg images don't have a size.
=> fix:osd: Make osd "Button" accept h and w props

navit/osd/core/osd_core.c
When max_speed changes while driving, the speed warner often announces unless I am decreasing speed. So I'd want to navit wait a little before complaining about my speed.
Another point is, that if navit places me on a road next to the e.g. highway/Autobahn I am currently on, it complains a lot while I am not breaking the speed limit on the road I am really on.
The timeout is based on position update. So if the position is updated once a second, navit will wait 10s before complaining about speed.
=> Add 10s timeout before speed warner talks to you

navit/osd/core/osd_core.c
In metric distance, all values between 10km and 1km were printed in meters. After this change all values over 100km are printed without the fractional part, between 10km and 1km in kilometers with fractional part and below that in meters as it was before.
=> Change format_distance to more proper values

navit/navit.c
This PR adds the feature to zoom out, look around and get back to autozoom after 10 gps updates. This will work with zoom in, too.
=> Pause the autozoom feature when zoom_in() or zoom_out() is called

CMakeLists.txt
disable the building of the pedestrian plugin by default for the Android port
=> Android: disable pedestrian default build

navit/xslt/iphone.xslt
I suppose https://github.com/navit-gps/navit/commit/f18e9dfb5110db7943d719ffe90171ac888326aa broke the build on the Navit server of the old iOS jailbreak packages.
Attempt to fix it.
=> fix old iOS jailbreak build

CMakeLists.txt
I'll merge this as soon as CI finishes.
=> Fix:port/android:Fix "invalid DT_NEEDED" warnings on API 23+, fixes #1348

navit/navit.c
Remove redundant sunrise/set test.
If the first test shows we are near a pole, it will never get to the second test.
If we are not near a pole, a second test will result in the same.
=> sunrise near poles simplification

CMakeLists.txt, ci/build_linux.sh, ci/build_tomtom_minimal.sh, ci/build_tomtom_plugin.sh, ci/run_linux_tests.sh, ci/setup_tomtom_requirements.sh, ci/xdotools.sh, navit/attr_def.h, navit/graphics/qt5/CMakeLists.txt, navit/graphics/qt5/QNavitQuick.cpp, navit/graphics/qt5/QNavitQuick.h, navit/graphics/qt5/QNavitWidget.cpp, navit/graphics/qt5/graphics_qt5.cpp, navit/graphics/qt5/graphics_qt5.h, navit/graphics/qt5/graphics_qt5.qml, navit/graphics/qt5/graphics_qt5.qrc
This pull request is about adding QML (QtQuick) Support to graphics_qt5 plug in.
A QML based graphics back plug in allows:
a) to easily add a QML based GUI
b) to integrate navit to Jolla Sailfish OS once, since QWidgets library is banned in Sailfish's Harbour shop.
This adds two build flags:
USE_QWIDGET:BOOL --> Enable QWidgets support (autodetected)
USE_QML:BOOL --> Enable QML support (autodetected)
Both can be set at the same time.
This adds one attr to graphics section in navit.xml:
qt5_widget -> set to "qml" for QML display, set to "qwidget" for qwidget display. Must only be set if both methods are present at the same time.
=> Qt5 Graphics: Add QML support

navit/gui/internal/gui_internal.c, navit/navit.c, navit/navit.h
When deactivating vehicle, profile is choosen from "car" vehicle_profile or by
default the first vehicle_profile in list. So, by example,
car_avoid_tolls never work when manually selecting current position (and
deactivate vehicle).
Now, if there is a selected vehicle profile, we keep it as
vehicle_profile (not changing it).
Aditionnaly, in internal gui, selecting a vehicle profile when wehicle
is deactivated, in gui_internal_cmd_set_active_profile(), call navit_set_vehicleprofile_name() with new
vehicle_profile (by name) before setting vehicle_attr to NULL (like in
gui_internal_cmd_set_position()).
Now, we can switch profile when vehicle is deactivatied and route is
update correctly.
TO DO : Same in other gui
TO TEST : with more than one vehicle enable
=> keep vehicle profile when deactivating vehicle

navit/vehicle/demo/vehicle_demo.c
Add 'Follow' and 'Active' to vehicle_demo to remove the corresponding error messages (Unsupported Attribute)
[trac1347](http://trac.navit-project.org/ticket/1347#no1)
The Demo_Vehicle complains about its unsupported attributes follow and active. These Attributes arent really unsupported but processes inside navit.c for all vehicles. Since these Attributes are processes globally we might want to ignore them inside vehicle_demo.c.
So this will be acheived by this PR.
=> Fix trac1347.

navit/navigation.c
On the path from orange (france) to valence (france) by highway,
the third roundabout after highway exit lead to central_angle=0, leading
to divide by 0 (near line 2488).
from osm_id : 160627295 to osm_id : 4277896
(delta1 + delta2) seams to be 360, so I just set roundabout_length to len in that
case.
=> :qnavigation_analyze_roundabout : central_angle may lead to division by 0

navit/gui/internal/gui_internal_keyboard.c
Since getenv may return NULL if a variable is not set, current keyboard
code crashes if LANG environment is not set.
=> Fix: Don't crash if LANG environment not set

CMakeLists.txt, navit/graphics/qt5/QNavitQuick.cpp, navit/graphics/qt5/QNavitWidget.cpp, navit/graphics/qt5/event_qt5.cpp, navit/graphics/qt5/graphics_qt5.cpp, navit/graphics/qt5/graphics_qt5.h, navit/graphics/qt5/graphics_qt5.qml, navit/graphics/qt5/graphics_qt5.qrc, navit/graphics/qt5/loader.qml, navit/gui/qt5_qml/CMakeLists.txt, navit/gui/qt5_qml/gui_qt5_qml.cpp, navit/gui/qt5_qml/gui_qt5_qml.qml, navit/gui/qt5_qml/gui_qt5_qml.qrc
This pull request aims to merge the work on a qt5 gui to main line.
This includes:
- The parts required to co work with the already functional qt5 qml graphics including the required changes to qt5 qml graphics. This gives a nice QML type for the navit render area.
- Some example skeleton code how to add more qml ressources.
- Basic gui plugin structure. Works as it replaces the QML code brought from graphics by its own.
Why to merge:
1. The outstanding changes to qt5 graphics hinder further development.
2. To give others the chance to kick in doing real GUI development, as I'm neither a QML nor a GUI expert. Everybody will see the stuff in trunk.
3. Even if never completed, the qt5_qml_gui code won't hurt, as it is just another plug in.
=> Add Qt5 qml gui skeleton

navit/navit_shipped.xml
Fixed some issues in ```Car``` layout where wood (```poly_wood```) was not showing up correctly inside towns (```poly_town```) and water (```poly_water```) was missing in parks (```poly_park```). Also fixed some discrepancy issues in the ```Car-dark``` layout.
=> Fix Car layout issues with wood and water

navit/graphics/qt5/loader.qml
Now the QML qt5 graphics happily rotates according to screen
orientation. At least on Sailfish. Should do on other QML hardware as
well.
=> graphics_qt5 QML: Add screen rotation support

navit/graphics/qt5/loader.qml
Welcome to Qt5 compatibility hell. Seems like the
Screen.orientationUpdateMask property is only valid from Qt5.4 and
beyond. To make this compatible down to Qt5.2, i introduce a QML
JavaScript workaround/hack.
=> Fix: Make rotating compatible to Qt 5.2

navit/navit_shipped.xml
Fix the base size of the android curser so the cursor drawing does not
draw out of the given space. Some graphics backends (like qt5) that have
real overlays don't like drawing out of the given overlay area.
=> fix: android cursor size

navit/navit.c, navit/xslt/osd_minimum.xslt
Suggestion for improving the out-of-box experience for builds using ```osd_minimum.xslt``` (Android and iPhone).
Depending on the ```autozoom_active``` setting (which is enabled by default on Android; https://github.com/navit-gps/navit/blob/trunk/navit/xslt/android.xslt#L52) the following paramers are set automatically:
- ```pitch``` (```pitch=autozoom_active==0?pitch:(follow>1?0:20)```)
- ```orientation``` (```orientation=autozoom_active==0?orientation:(follow>1?0:-1)```)
And a new OSD element is added:
- _Zoom auto_ or _Zoom manual_ (depending on active setting/```autozoom_active```)
Initial startup: **auto mode; driving/navigating**:
Because autozoom is active by default, this sets the ```pitch``` to a value of 20 for a 3D look. ```orientation``` is set to -1 so the map rotates in the …
=> Auto pitch and orientation + Apply pitch correction in reverse when reading attribute

navit/maptool/osm.c
This branch allows map to include towns to more than one country. There are a few regions in the world mapped in such a manner, and stock maptool leaves only one of the countries active, randomly ignoring the rest.
We have a planet built with this branch, it's available for download at http://maps6.exp.navit-project.org/
=> Maptool multicountry towns

navit/vehicle/file/vehicle_file.c, navit/vehicle/webos/bluetooth.c, navit/vehicle/wince/vehicle_wince.c
NMEA messages starts with '$' followed by 2 digits that indicates
the Talker ID. The most common was GP for GPS, but now many modules
can use other satellites systems or even 2 systems at the same time.
Other Talker IDs are:
- GL:russian GLONASS
- GA: european Galileo
- BD: chinesse BeiDu
- GN: Global Navigation: a combination of 2 or more systems.
=> Patch:core:More Talker IDs other than GP accepted

contrib/sailfish/navit-sailfish.spec, navit/xslt/sailfish_gui.xslt
Navit medium GUI icon size fix
This changes the medium size icon for HMI to 64x64px. This is necessary
because of changed icon set and therefore different icon default sizes.
Otherwise the icons on POI screen were way too big.
=> Sailfish icon size fix

ci/setup_android.sh
This pull request adds a workaround to the CI because current platform tools from google are broken.
This fixes Ticket #1354
(This is the replacement for PR #356 because I had a problem with my repo)
=> Add self checking workaround for android platform tools

navit/gui/gtk/gui_gtk_statusbar.c
modified:   navit/gui/gtk/gui_gtk_statusbar.c
The status bar under GTK was only showing metric units. So I coded up a fix.
I tested as follows:
* Initialized the local variable imperial to true. Had imperial set to one in my navit.xml. Got imperial measures, as expected.
* Changed the local variable initialization to false. Recompiled and ran. Got imperial, as expected. This indicates that the function collected it as expected.
* Changed the attribute in navit.xml to 0. Ran again. Got metric units as expected.
=> fix:gtk:fixed missing imperial units in the GTK ui.

.circleci/config.yml
Needed to get doxygen.navit-project.org to point to the Github-hosted content.
=> fix:doc:ensure that the custom domain is set for doxygen

ci/build_android.sh
With CI v1 we were building release apk in `master` and debug apk everywhere else (including `trunk`).
With CI v2 we currently don't push from trunk to master automatically, thus our play store releases are lagging behind.
=> change:android:always build apk release

navit/CMakeLists.txt
This PR fixes the issue that navit.dtd could not been copyed on android build which caused the build to fail sometimes.
Also i reworked this file to use 3 spaces anywhere
=> fix:cmake:Rework of xslt convert process

contrib/sailfish/build_on_sailfish_sdk.sh, contrib/sailfish/navit-sailfish.spec
This pull request enables Navit to be built on newer Sailfish SDKs which uses different tool paths than before. Beside that is adds now mandatory build requirement "git".
=> Sailfish build on newer SDKs

navit/gui/gtk/gui_gtk_action.c
This should fix http://trac.navit-project.org/ticket/1357 I tested for
follow_vehicle set to zero and one, and absent.
modified:   navit/gui/gtk/gui_gtk_action.c
=> fix:gtk:Initialize Follow menu entry correctly.

cmake/version.cmake
This fixes the wince build and all builds where one of the two git commands would fail.
=> fix:cmake:Fix getting the version from git to fix the wince build

ci/update_download_center.sh
Repo download on the wince docker image was broken due to really old ssh lib and git client
=> fix:fix download center for wince

navit/navit_shipped.xml
On the T@H layout theme, oceans and seas are not displayed:
This patch fixes this:
=> fix:XML: Adding missing sea/ocean display in T@H layout theme

.circleci/config.yml, ci/setup_wince.sh
Because the image is to old we need to install git-core after the code checkout.
With this the WinCE build is fixed **and** able to push to the download center
=> fix:ci:Fix Wince download center upload

man/navit.1
Fixing a minor typo in the man page for navit:
information is a non-count noun, so the convention is that information is both singular and plural
=> doc: fix misspell

navit/maptool/tile.c
Based on cppcheck's warning:
```
[navit/maptool/tile.c:516]: (error) Common realloc mistake: 'th' nulled but not freed upon failure
```
=> maptool: prevent issues when realloc fails

navit/maptool/tile.c
When writing aux files, if the fread fails, we don't free the buffer, which could cause some memory leaks.
This PR also contains  a cosmetic change on spacing to be coherent with the rest of the code for that block of code.
=> maptool: prevent memory leak when fread fails while reading aux files

navit/osd.c, navit/osd.h, navit/osd/core/osd_core.c
This PR shall fix [trac-1202](http://trac.navit-project.org/ticket/1202).
After looking into it again after a year, I could fix the behavior for Image and Scale.
Additionally I renamed the OSD flags to what they probably do.
I took a new branch (with typo -.- ) because we do not want to see all commit from the past  year. 
#235 can stay closed.
=> PR to fix Trac 1202 (Make Image and Scale osd types obey osd_configuration setting)

navit/maptool/buffer.c, navit/maptool/ch.c, navit/maptool/google/protobuf-c/protobuf-c.c, navit/maptool/maptool.c, navit/maptool/misc.c, navit/maptool/osm.c, navit/maptool/osm_protobuf.c, navit/maptool/osm_protobufdb.c, navit/maptool/tile.c, navit/maptool/zip.c
Closes: #427.
Migrating the `malloc` to `g_malloc` and removing some asserts already done by `g_malloc`.
The other operations will come later in another PR.
=> maptool: migrate malloc/free/realloc to g_malloc/g_free/g_realloc

contrib/sailfish/build_on_sailfish_sdk.sh, contrib/sailfish/navit-sailfish.spec
This bumps version for navit to 0.5.1-r5
This removes gcc from build dependencies
This automatically zyppers in build requirements as given in spec file
into sailfish build virtual machine. So no hand work required anymore.
=> New version for sailfish 0.5.1-r5

.github/ISSUE_TEMPLATE.md
Every time people will open an issue on Navit they will see a link to our wiki.
=> Github: Add a template for github issues

.circleci/config.yml
Currently master is about 190 commits behind trunk.
I think this should work
=> Add:CI:Re-add the merge to master job when circleci runs on trunk and is successful

.circleci/config.yml
This is to fix https://circleci.com/gh/navit-gps/navit/6041
and to make sure that we only merge if all the CI build jobs passed.
=> Fix the merge to master in circleci and require that all build passed

.circleci/config.yml
@jkoan pointed out with good reasons that it would be better to only run the doxygen job when the builds are all passing. This is the corresponding PR.
Putting @pgrandin as reviewer to make sure there were no specific reasons to put this one in a separate workflow.
=> Change:CI:Move doxygen to the build workflow to only run it when the build succeeds

ci/build_win32.sh, ci/import_translations.sh, ci/merge_i18n_update.sh, ci/publish.sh, ci/setup_android.sh, ci/setup_common_requirements.sh, ci/xdotools.sh
Updated all the ci scripts to have a shebang and use `set -e` except for `ci/update_download_center.sh` who has a retry mechanism that prevents us from using `set -e`.
Also fixes an error happening when extracting the android sdk as the owner of the extracted files is not the same as in the tarball.
=> Update:CI:Make sure that all the scripts in the ci folder have a shebang and use set -e

.mailmap, AUTHORS, ci/generate_contributors.sh
Hi guys,
This PR adds a script to update the AUTHORS file based on the git lofs.
It has a mechanism to remap the users identified as duplicates and identified retired contributors as the ones without any commit over the last 2 years.
Also updated the AUTHORS file at the same time so you'll see the result.
Let me know what you think about it.
Thanks!
Joseph
=> Add a script to update the contributors list from the git log

.circleci/config.yml, ci/setup_common_requirements.sh
I suppose we don't need both imagemagick and librsvg2-bin for the liunx build,
changed to librsvg2-bin for all.
=> CI xxsmal cleanup

navit/debug.c
When using the dbg(log_error, ...) function, I now get segfaults.
The bug has been introduced at commit 221f783ea1caaaab2f5ceadc6b0fb3e720aac3df
g_strconcat's arguments should be a list of pointers, the last has to be NULL.
I have reworked the append so that it does not require a temporary allocation of the format string, but rather adds EOL characters manually.
I changed the hardcoded 4095 to a sizeof() call which is more future-proof in case the buffer size is updated in the future.
I finally, I also force \0 termination of the resulting string (maybe there could be issues if the message is longer than the 4095 bytes of the buffer). Please review this last point as it is maybe not really needed.
=> Fix:debug:Correction on segfault in debug_vprintf() introduced in 221f783e

navit/xmlconfig.c
So I wasn't sure if we should g_strndup instead of strncpy or directly g_strdup and drop the string length altogether. Any thoughts?
Also does the xml support utf8? In this case I would have to use g_utf8_strncpy.
Thanks!
=> Update:xmlconfig:Move from malloc/free/strncpy to g_malloc/g_free/g_strndup

navit/vehicle/wince/vehicle_wince.c
In #575 I noticed that this header seems unused, so cleaning it up.
=> cleanup:wince:remove unused ConvertUTF.h header

navit/track.c
This PR fixes traffic replay from an nmea file converted from the default navit gpx logs.
Time is not logged by default in our log config, so replaying traffic wasn't working as expected.
=> fix:core:fix log replay

README.md
Remove overused space characters from README.md to comply with English language.
=> Remove overused space characters drom README.md

CMakeLists.txt
Removes the unused dependency on libpng from the Android build.
Anybody feel free to set a correct title for this accordigng to the guidelines, maybe I will learn myself someday ....
=> cleanup:android:remove unused dependency libpng

.gitignore
After upgrading to Eclipse Oxygen (previously on Luna) and encountering several issues, I learned that CMake’s project generator for Eclipse is unmaintained and Eclipse’s maintainers advise against using it, as there have been issues with it. The recommendation is to use cmake4eclipse instead.
I have tried it and found it not only fixes the issues I was experiencing, but also does away with the limitations we had in the past:
* Source files no longer appear in two different places in the tree, leaving you to wonder which is the correct one to edit
* As `CMakeLists.txt` is the single source of truths, changes to the CMake setup take effect instantly (presumably—not yet tested in practice)
* Team features (git access from Eclipse) are now available
I have created a draft for an updated …
=> Add:build:Add cmake4eclipse artifacts to .gitignore

navit/navit.dtd
This PR fixes the navit.dtd
Test Command:
xmllint --noout --dtdvalid navit/navit.dtd navit/navit_shipped.xml
Output before:
> `navit/navit_shipped.xml:36: element navit: validity error : Element navit content does not follow the DTD, expecting (graphics , gui+ , log* , osd* , vehicle* , tracking , vehicleprofile* , route , navigation , speech , mapset+ , layout+)*, got (graphics gui gui log osd osd osd osd osd osd vehicle vehicle tracking vehicleprofile vehicleprofile vehicleprofile vehicleprofile vehicleprofile vehicleprofile vehicleprofile vehicleprofile route navigation speech mapset mapset mapset mapset layer layout layout layout layout layout layout layout )
> Document navit/navit_shipped.xml does not validate against navit/navit.dtd`
RC: 3
After the Patch:
> ` `
RC: 0
=> fix:config:Fix dtd to allow real xmlint

navit/maptool/buffer.c
=> fix:maptool:coverity #262887 - leaked_storage: Variable f going out of scope leaks the storage it points to.

.circleci/config.yml, scripts/ci_sanity_checks.sh, scripts/setup_common_requirements.sh
The idea of this is to add a sanity check before even the builds start.
This just remove the trailing spaces and runs astyle with what we did in #569 and #605.
It could be, for example, extended with the nice work @jandegr is doing on checkstyle with Java.
=> add:ci:Add sanity check script on circleci

navit/gui/internal/gui_internal_keyboard.c
This patch adds a underscore key ('_') to the internal GUI keyboard. The underscore is necessary to search for POI types, for example poi_shop_bicycle.
Thank you for merging.
=> Add underscore to internal gui keyboard.

scripts/ci_sanity_checks.sh
This PR:
* Adds a check for the xmllint if modified in the PR as a follow-up from #583
* removes the `set -x` so that it has a more understandable output
* makes sure that the diff is done for each check and each file, not just one big diff that would make it less understandable
* only run the check on each file once (using `| sort | uniq`)
* show all the errors before exiting (so I had to remove `set -e`)
* add a warning in case people try to run it locally
=> update:ci:Refactor the sanity check for better output and add xmllint check

navit/graphics/win32/graphics_win32.c
This PR gets rid of the following compilation warnings for win32
```
/root/project/navit/graphics/win32/graphics_win32.c: In function 'pngdecode':
/root/project/navit/graphics/win32/graphics_win32.c:1132:19: warning: variable 'alpha_present' set but not used [-Wunused-but-set-variable]                                                                       
int           alpha_present;
^
/root/project/navit/graphics/win32/graphics_win32.c: In function 'pngscale':
/root/project/navit/graphics/win32/graphics_win32.c:1292:12: warning: variable 'origPixels' set but not used [-Wunused-but-set-variable]                                                                          
png_byte *origPixels;
^
/root/project/navit/graphics/win32/graphics_win32.c: In function 'graphics_win32_new': …
```
=> cleanup:win32:Remove unused variables

contrib/sailfish/build_on_sailfish_sdk.sh, navit/android/change_xslt.sh
This PR removes the warnings in codefactor about "Useless cat usage": https://www.codefactor.io/repository/github/navit-gps/navit/issues?category=Performance&groupId=1692
Note that it also remove unnecessary copy and redirect of temporary file by using the "in-place" capabilities of sed.
=> update:style:optimize the usage of cat in shell scripts

navit/startonce.sh, scripts/build_tomtom_minimal.sh, scripts/build_tomtom_plugin.sh, scripts/xdotools.sh
Most of those scripts are forcibly started with bash anyway.
This should solve the codefactor issues: https://www.codefactor.io/repository/github/navit-gps/navit/issues?category=Compatibility&groupId=1669
=> update:scripts:change the scripts that use non-POSIX functionnalities to bash

navit/script/cabify.sh
Removes a warning in codefactor: https://www.codefactor.io/repository/github/navit-gps/navit/issues?category=Maintainability&groupId=1697
=> update:scripts:avoid iterating over ls output by using glob

scripts/setup_wince.sh
This adds a forgotten `!` in the shebang. Fixes: https://www.codefactor.io/repository/github/navit-gps/navit/issues?category=Maintainability&groupId=1694
=> fix:scripts:fix malformed shebang

scripts/import_translations.sh
egrep is officially deprecated, see: https://www.gnu.org/software/grep/manual/html_node/grep-Programs.html#grep-Programs
This PR moves its usage to `grep -E` as recommended.
Fixes: https://www.codefactor.io/repository/github/navit-gps/navit/issues?category=Maintainability&groupId=1680
=> cleanup:scripts:removes deprecated usage of egrep

contrib/sailfish/build_on_sailfish_sdk.sh
Whatever the 'enhancement' done in #612 should bring, it causes grep
to complain for non existing file in Sailfish's MER SDK.
Most probably because the escaping of the parenthesis was wrongly
considered. Never mind - revert.
=> Revert #612 for sailfish build script

scripts/ci_sanity_checks.sh
As requested in #624, removes checking for trailing spaces and other style-related elments on `navit/support`. Also added `navit/fib-1.1` to it as it is a 3rd party lib.
Note: the indentation change is just to make sure we're also using 4 spaces indentation in the script (I was using 2 spaces before).
You can use the diff settings button when reviewing to get rid of the white spaces diffs which makes the review way easier.
=> update:scripts:change the sanity script to exclude fib and support

navit/xslt/wince.xslt, scripts/build_wince.sh, scripts/setup_wince.sh
Remove inclusion of sample map in zip package (which, in addition, fails currently because map server is down)
Allow running build_wince.sh script twice by performing cleanup on directories if already created
Adding missing espeak-data to zip package (the content of this directory is currently missing in WinCE output package and makes navit speech synthesis fail unless manually copied on the WinCE device)
=> Fix:scripts:WinCE build script (remove sample map, add espeak-data)

navit/graphics.c
Circles are not that smooth on platforms without native support for circles.
On these platforms, circles are actually drawn using multiple segments.
Improving definition of small radius circles.
Also, I renamed function `draw_circle()` because it does not draw a circle but rather creates a set of points that represent a circle or an arc.
I also took the opportunity to add doxygen comments on related functions and fix a few comments.
=> Refactoring:graphics Improving quality of circles on platforms without native circle method

navit/graphics.c, navit/gui/internal/gui_internal.c, navit/route.c, navit/util.c, navit/util.h, navit/xslt/android.xslt
When selecting GPS coords or a town/street, and choosing "View on map", the display is centered on the selected location, but there is no visible pointer on this location.
In order to implement this, I have am re-using the code that is already existing to handle action "Show results on the map", and that is already able to display multiple result pointers on the map.
Here is an example of the result when selecting "View on map" for "An der Hauptfeuerwache" in Mûnchen.
I added some code to split long strings to multilines, in order to avoid having the text spread too much accross the map. This is also useful when using GPS coords:
=> Refactor:gui/internal: Add pointer and label when using function "view on map"

scripts/pre-commit
Related to #569: This PR adds a pre-commit hook example script that removes trailing spaces, control-M and uses astyle to reformat files automatically.
Instructions are in the header.
This is not something mandatory and we'll probably need to mention it in the doc when we update it.
=> add:helper:Add a pre-commit hook script for users to use locally

.gitignore
Hi,
just a very small change - I'd like to have the nbprojects folder netbeans uses for its project included in .gitignore.
Thanks ;)
=> Add netbeans project folder to gitignore

navit/gui/internal/gui_internal.c
Feature was introduced in SVN r1456 (commit 5dea1c6d5ea177a39ba0a9ce29cd247a30005960) but was not applying tag properly from config file
=> Fix:gui/internal:Handling "spacing" attribute properly for tag <gui type="internal">

navit/maps/CMakeLists.txt
This fixes the CMP0026 warning from cmake:
```To configure your build use 'cmake -L' to find changeable variables and run cmake again with 'cmake -D <var-name>=<your value> ...'.
CMake Warning (dev) at navit/maps/CMakeLists.txt:5 (GET_TARGET_PROPERTY):
Policy CMP0026 is not set: Disallow use of the LOCATION target property.
Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
The LOCATION property should not be read from target "maptool".  Use the
target name directly with add_custom_command, or use the generator
expression $<TARGET_FILE>, as appropriate.
This warning is for project developers.  Use -Wno-dev to suppress it.
```
Local Build Log: https://gist.github.com/jkoan/ef8723cb99e438b74f2affa3b9fc8db2
=> build:maptool:Fix cmake CMP0026 warning

.circleci/config.yml
After we merged the gradle build with #553 we havent updated the download center with new data from android builds. This should fix it once merged.
=> Readd Navit Download Center for Android

scripts/update_download_center.sh
Currently our download center does not have the last build because it's sorting is alphabetical instead of numerical. And this can't be fixed easily with jekyll itself, but a easy solution is to do a padding on the filenames before we upload them to git. This PR should fix this.
=> fix:build:Pad metadata files so jekyll sort works corect

scripts/import_translation.sh
This ensures that we don't commit translation updates with extra spaces at the end of the line. It should avoid having the CI fail on the sanity checks.
=> fix:i18n:remove extra whitespaces when importing translations

.circleci/config.yml, scripts/build_win32.sh
Since no people are interested to update image, this quickfix the cmake version on old 14.04 for win32 target.
=> circleci:add ppa for cmake 3.x on win32 target

.circleci/config.yml
Previously the sailfish build was not using the standard checkout command which could not handle pull requests in a proper way. The PR fixes this.
=> fix: replaced custom git clone command by standard checkout command

navit/route.c, navit/traffic.c, navit/traffic.h
Fixes a crash in the traffic module if no matching segments are found for a traffic condition.
For three-point locations (from–via–to), if no segments are found for from–via, then via–to is used.
=> Traffic: Improve handling of situations where no segments are found

.circleci/config.yml
In Android build by circleci, icons for 192 and 256px are not built, which, altogether with https://github.com/navit-gps/navit/issues/584 makes icons be displayed with the worst available resolution.
This PR adds high resolution icons during build.
It also fixes successive builds on circleci for android where a rename command applies to all files, including Makefiles, and makes subsequent builds fail.
=> circleci:Android: adding high resolution icons and improving rename steps

.circleci/config.yml, navit/graphics.c, navit/maptool/boundaries.c, navit/maptool/osm.c, scripts/build_android_arm.sh
This PR moves the entire Android build process to a separate shell script. The script is used by CircleCI but can also run locally on Linux if all build dependencies are in place.
The script is designed to exit with an error if any of the build steps fails (a different error code for each step), close to present behavior.
Benefits:
* An official build script for local builds (not sure how others did that, but I had to maintain my own local build script, which was tedious)
* Changes to the build process can now be tested locally before committing
* If the CircleCI build works, local builds likely will, too, and vice versa
* Changes to the build process affect both local and CircleCI builds (which reduces the likelihood of 
changes breaking your local build)
Some cleanup was necessary …
=> Move Android build to separate script

navit/graphics/qt5/QNavitQuick.cpp, navit/graphics/qt5/QNavitQuick.h, navit/graphics/qt5/QNavitWidget.cpp, navit/graphics/qt5/QNavitWidget.h, navit/graphics/qt5/event_qt5.cpp, navit/graphics/qt5/event_qt5.h, navit/graphics/qt5/graphics_qt5.cpp, navit/graphics/qt5/graphics_qt5.h
Do not clear overlay contents if resize is called for them, but the actual geometry doesn't change.
This happens on resize if the overlays are repositioned. Now OSD's do not loose elements any more.
Apply astyle to comply with coding style and to tame CI
=> Fix:graphics_qt5:fix overlay handling

navit/navit_shipped.xml, navit/xslt/android.xslt
This enables the traffic plugin by default on all platforms via the XML config file.
On Android, the `traff_android` plugin is used and any traffic updates received via TraFF broadcasts are processed.
On all other platforms, the `null` plugin is used. This plugin enables traffic message processing but will never supply any messages. On Linux this allows injection of TraFF messages via dbus (while this functionality could be [ab]used for a traffic supplier, it is intended as a test interface).
Users with a custom navit.xml will not be affected by these changes until they adapt their configuration accordingly.
So far these plugins have been tested on Linux and Android. Tests on other platforms would be welcome (though I expect regressions to be quite unlikely here).
=> Enable traffic plugins by default

navit/android/src/org/navitproject/navit/Navit.java, navit/android/src/org/navitproject/navit/NavitGraphics.java
According to blame, this particular chunk of code was added by Rikky (who seems to be no longer active) in 2011, and seemed to be a precautionary measure to prevent unclean shutdowns.
However, this prevented Navit from resizing properly, as resizing destroys the activity and then recreates it—the latter being prevented by Navit exiting. This explains why Navit would not work in multi-window mode. (Tested on Anbox, where this change will make Navit resize properly rather than exiting on any attempt to change the window size.)
Most likely we do not need that precautionary measure any longer: 85b9d5da already replaced the call to `finish()` in the `Navit#exit()` method with a call to `NavitDestroy()` (to prevent unclean shutdowns), and any non-Android quit operation should cause the process …
=> Make Navit work in split screen mode

navit/android.c, navit/android.h, navit/android/src/org/navitproject/navit/Navit.java, navit/android/src/org/navitproject/navit/NavitGraphics.java, navit/android/src/org/navitproject/navit/NavitSpeech2.java, navit/plugin/pedestrian/pedestrian.c, navit/traffic/traff_android/traffic_traff_android.c, navit/vehicle/android/vehicle_android.c
Fixes #750. This significantly improves performance when the window dimensions change (as happens when entering or leaving split-screen mode, or when rotating the device), and also fixes some resource leaks and potentially a race condition.
Developed and tested on Anbox, as well as some brief tests on a real device.
=> Android: Do not reinitialize everything when the activity is recreated

navit/android/res/values/strings.xml, navit/android/src/org/navitproject/navit/Navit.java
Fixes #640. This restores the notification icon on API 26+ (Oreo and up).
I had to change the `NotificationCompat.Builder` in `Navit.java` to `Notification.Builder` as the latter allows us to specify a notification channel on API26+. `NotificationCompat.Builder` would require us to use version 26+ of the compatibility library (we currently use version 24), requiring us to increase the minimum SDK version.
`Notification.Builder` seems to work (tested on LineageOS 15.1), so I would stick with that unless someone can give me a compelling reason why we need `NotificationCompat.Builder`.
=> Fix:port/Android:Create notification channel on API 26+

navit/speech/android/speech_android.c
On some versions of Android, I found out that hyphens were pronounced textually by the speech processor.
For example, on Android 5.1, in french, I get "Saint ... trait d'union ... Germain" pronounced for "Saint-Germain".
This patches the text before getting into the speech processor, so that there are no hyphens anymore.
=> Fix:Speech:Android: Replace hyphens with white spaces when using android speech

navit/graphics/sdl/graphics_sdl.c
Currenty the window created by the SDL driver cant be closed with wihe window X button.
This fixes this issue
=> fix:graphics:Fix issue when try to close the SDL window ion non webos

navit/attr_def.h
As discussed in #771 and requested by @mvglasow hers the same fix for attr_def.h
=> Fix:core:Fix Warning in IDE for Items not found

navit/item_def.h
Hi, 
always when in a IDE like Eclipse i head the problem that all attr_* definitions where not found by the IDE and therefore where marked as error, so my approach now is to declare them as extern so the IDE does not get annoyed by this. This also fixes auto competition.
=> Fix:core:Fix item_def.h when used whithout defined macros (like in IDE)

navit/gui/internal/gui_internal_command.c
This is some preliminary work for re-using this escape function also in Android code.
Code will thus be moved as a generic (non-static) utility function global for Anroid and internal GUI.
I also added doxygen doc, and made the algo more readable (or at least, I consider it to be)
=> Add:Gui/Internal: Adding missing escape modes and fixing generic html escape mode

CONTRIBUTING.md
I think it makes sense to start putting elements to contribute to the code inside the `CONTRIBUTING.md` document to centralise that a bit more like every other project do.
This PR migrate the https://wiki.navit-project.org/index.php/Submitting_patches document from the wiki to here and do some updates on it.
=> update:doc: add the submit patches section from the old wiki close to the code

navit/bookmarks.c
As a followup for #435 heres a version which fixes the Problem for all Plattforms. 
Original Text from @pgrandin:
> When using navit on some devices that could loose power without being properly shut down, the bookmark files was lost (content was empty).
> 
> This problem is reproduceable : running Navit on a buildroot image on the raspberry pi (for example one built using https://github.com/navit-gps/buildroot ), if the pi looses power and the bookmark file has been modified, the bookmark file will be lost everytime.
> 
> This simple fix ensures that the files get flushed to the disk when we write the bookmark files, and solves the issue according to my tests.
=> Sync bookmarks 2

CONTRIBUTING.md
I think the rest of the Programming guidelines should probably go to a "Development" section in ReadTheDocs as it's a bit bigger.
Just took parts of the Contributing section of the Programming guidelines to put here what was missing.
=> update:doc: Update the contributing.md to add the contributing section of the Programming guidelines

CMakeLists.txt
After updating I noticed that now maptool seems to hard depend on protobuf-c. This fix disables maptool if protobuf-c is not found, but allows to build the rest of navit as usual.
=> Disable maptool if protobuf-c not found

navit/graphics/qt5/QNavitWidget.cpp, navit/graphics/qt5/event_qt5.cpp, navit/speech/qt5_espeak/Qt5EspeakAudioOut.cpp, navit/vehicle/qt5/vehicle_qt5.cpp
This commit removes moc file includes for some classes which do not
define new qt classes. This caused a long standing warning which seems
to be treated as error on some setups.
Additionally a small fix to make nit-picky gcc 8 happy.
=> qt5: Remove unnecessary moc includes.

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, docs/development/programming_guidelines.rst, docs/index.rst
Migration from https://wiki.navit-project.org/index.php/Programming_guidelines to readthedocs
Created a section specific for developers to make things clearer.
=> Migrate the programming guidelines documentation to readthedocs

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
The readthedocs url is available for the trunk branch but not the latest tag in readthedocs so let's use that branch instead.
=> update:doc:Fix the readthedocs url for the development guidelines

navit/attr_def.h, navit/callback.c, navit/callback.h, navit/graphics.c, navit/graphics.h, navit/graphics/qt5/graphics_qt5.cpp, navit/xslt/sailfish_cursor.xslt, navit/xslt/sailfish_qt5.xslt
This pull request adds dpi scaling to navit's graphics layer. It basically allows to convert the internal measurement unit (traditionally 1:1 pixels) into something virtual. You can specify the dpi value your layout / OSD was designed against in virtual_dpi, effectively assigning the internal pixel a human unit.
Then it will get the screen dpi value (or you can override that in config) to scale your setup to your real hardware dpi. Hardware dpi support is given for qt5 and gtk, but not widely tested yet.
Of course best results if real_dpi is a even multiple of virtual_dpi 
This can be used as a basis for supporting human units (like millimeters, inches, android dip) in config files as well, since these can be converted using virtual_dpi.
This is the second attempt after #810 . But #810 …
=> add:graphics:dpi scaling support

navit/main.c, navit/main.h, navit/navit.c, navit/start_real.c
This commit corrects the default layout handling broken when splitting
the layouts to own files. It restores the layout saving of the internal
gui. So now it starts again with the last selected layout honouring
gui_internal.txt
=> fix:core: Correct default layout handling.

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, docs/development/commit_guidelines.rst, docs/index.rst
Migrates https://wiki.navit-project.org/index.php/Commit_guidelines to readthedocs
=> Add:doc:Migrate the commit guidelines document to readthedocs

navit/script/cabify.sh, navit/startonce.sh, navit/tools/cleanattr.sh, scripts/basic_upload_apks.py
This is a cleanup of the errors `Check exit code directly with e.g. 'if mycmd;', not indirectly with $?` found in codefactor: https://www.codefactor.io/repository/github/navit-gps/navit/issues/trunk?lang=1#
Nothing really exciting there.
=> Refactoring:tools:minor Check exit code directly with e.g. "if mycmd;", not indirectly with $?

navit/navit_shipped.xml
Fixes a typo on the tradermarked name of OpenStreetMap.
I was curious after seeing #849 to see if we had some in the code so I found this one.
=> Refactoring:xml: Fix a typo of the OpenStreetMap name in the shipped XML

navit/navit_shipped.xml
This improves bike routing (see also #844): 
* Oneway restrictions are respected for bikes (if a way has different oneway restrictions for bikes, create two ways, one for each direction, and set access flags accordingly)
* Trunk roads are allowed if access flags permit, but with a low priority
* Unpaved paths get a low speed and priority so paved paths are preferred
* Priority decreases as road order increases
Tests with the use cases in #844 show significant improvements over the previous situation. There may not be a perfect solution because:
* We do not have elevation information so we cannot consider that for routing.
* We do know if a way where both pedestrians and bikes are allowed is segregated (we would prefer segregated ways for routing), or if a designated bike path runs right …
=> Fix:xml:Fix bike routing

navit/graphics.c
As some simple graphics like SDL or windows CE do not clip on drawing, the rendering performance of huge (not necessary in node count but on screen) polygons with holes cause poor drawing performance even if only small portions of those polygons are on screen.
To fix this we clip polygons with holes before calling back end to draw like done with traditional polygons as well.
=> fix:core:add clipping to polygons with holes

navit/graphics/qt5/graphics_qt5.cpp
There is a "misconception" in qt5 graphics about how to draw transparent stuff causing transparent items on the map to not correctly work. This PR changes qt5 graphics to force-clear overlays on starting to draw them instead of force clearing the shape of a transparent item. While this imposes the limitation that the content of an overlay cannot be drawn in multiple runs, it allows to draw transparent stuff on the map.
Luckily I don't know of any overlay item yet that is not drawn in one run. So this seems to work OK.
=> fix:graphics/qt5; Allow to draw transparent polygons

docs/development/linux_development.rst, docs/index.rst
Migrating:
https://wiki.navit-project.org/index.php/Linux_development
https://wiki.navit-project.org/index.php/Dependencies
https://wiki.navit-project.org/index.php/OpenSuse_dependencies
https://wiki.navit-project.org/index.php/Gentoo_dependencies
https://wiki.navit-project.org/index.php/Debian_dependencies
https://wiki.navit-project.org/index.php/Ubuntu_dependencies
https://wiki.navit-project.org/index.php/Fedora_dependencies
I copy/pasted those making very small edits. They probably do need more than that but the migration phase is done and it'll be easier to work on further enhancements when in the repo.
=> update:doc:Migrating linux development and dependencies from the old wiki

docs/development/commit_guidelines.rst, docs/development/macos_development.rst, docs/development/programming_guidelines.rst, docs/development/wince_development.rst, docs/development/windows_development.rst, docs/index.rst
Migrating
https://wiki.navit-project.org/index.php/MacOS_development
https://wiki.navit-project.org/index.php/WinCE_development
https://wiki.navit-project.org/index.php/Windows_development
And fixing some formatting.
=> add:doc: Migrate MacOS, Windows and WinCE Development pages to readthedocs

navit/attr_def.h, navit/color.h, navit/graphics.c, navit/layout.c, navit/layout.h, navit/navit_layout_bike_shipped.xml, navit/navit_layout_car_android_shipped.xml, navit/navit_layout_car_dark_shipped.xml, navit/navit_layout_car_shipped.xml, navit/navit_layout_car_simple_shipped.xml, navit/navit_layout_th_shipped.xml, navit/xslt/sailfish_svg.xslt
This pull request adds the possibility to globally set a default for icon size of a layout.
You can now give "icon_h" and "icon_w" properties in "layout" tag. This causes navit to not use the real size of an icon but to scale it to have the requested size. Guessing prescaled icons (the name_w_h.png's of course works. Default size of 22x22px which is the default size hint on most of the svg's is used. This fixes #819.
This pull request adds the property "underground_alpha" to the "graphics" tag giving the alpha value to use as transparency if ways are flagged with AF_UNDERGROUND. This effectively renders tunnels in transparent.
This pull request adds a "oneway" tag to itemgras in layouts. Together with the enhancements of the "arrows" itemgra used for drawing the route graph one can print …
=> fix/enhancement:graphics/layout:get default icon size from layout + draw tunnels transparent + mark oneway streets

navit/navit_layout_car_shipped.xml
With the introduction of the multipolygon code we now have all the nice landuses in the map. However, in OSM there are some map features that are not mapped as multipolygon but just "above" the other landuses. Like poly_zoo, poly_theme_park or poly_airfield.
Current configuration causes them to be hidden by the landuses, as these are drawn after the above mentioned. OSM's Mapnik style solves the problem by drawing those feature transparent above the landuses.
This pull request does so for some map features as well causing the map to look way better.
If transparent drawing is not supported by the platform, this causes the mentioned polys to be drawn above the landuses, showing them, eventually hiding some landuse details underneath. But this looks even better than before too.
NOTE: …
=> enhancement:layout_car:use transparency to draw some map features

navit/vehicle/file/vehicle_file.c
vehicle_file_close(priv) disables watch of the file.
vehicle_file_open(priv) dont reenable it. So the gps position was frozen
In my case it is suspend/resume which lead to GPS the reopen.
=> Add watch after reopen the gps file

.circleci/config.yml, navit/navit.dtd, scripts/ci_sanity_checks.sh, scripts/setup_sanitycheck_requirements.sh
and reenable xml lint for all configurations shipped. To do this the navit.dtd model is updated by the new properties added.
=> fix:circleci: do not download build environment for sanity check

navit/graphics.c
This commit prevents c_alloca from flooding the stack if we have to deal
with really huge polygons. Use slower g_malloc instead.
=> fix:core:prevent stack overflow on drawing huge polygons

CHANGELOG.md
I'm trying out some new tool (https://github.com/github-changelog-generator/github-changelog-generator) to generate the changelog based on the PR instead of the commits (some PR have hundreds of commits making the changelog quite unreadable.
We should probably re-work some PR titles to make them more relevant and reorganize the PR around the different sections that we had under the previous releases.
We could also reorganize the changes by components (graphics, traffic, core, etc)
Note: I removed from the changelog the minor cleanup/typos and the docs-related PR.
Let me know what you think.
It would look like: https://github.com/navit-gps/navit/blob/aerostitch/changelog/CHANGELOG.md
=> Prepare changelog for release 0.5.4

.circleci/config.yml
Storing translations was added to the android build on CI a long time ago to debug a specific issue.
It takes up to 30 seconds but is not needed anymore.
relates to https://github.com/navit-gps/navit/issues/910
=> CI:cleanup

contrib/sailfish/build_sailfish_ci.sh
In order to reduce the time spend in building navit for sailfish I disabled as discussed in  #910 the compilation steps for the i586 platform.
=> Disable building of navit for sailfish on i586 platform

navit/maptool/zip.c
This fixes the zip64 central directory created by the maptool.
While the broken one works on navit, it failed to extract with usual zip
tools due to parts of the zip64 end of directory part not being filled
correctly with values.
This happens on all 64 bit zip files generated by maptool including the sample map since the multipolygon patches.
Files downloaded from planet extractor are and always have been corrupt as well. Without the source of the planet extractor, I don't know if this actually fixes the files shared by planet extractor as well.
=> fix:maptool:create valid zip64 central directory

navit/maptool/itembin_buffer.c, navit/maptool/maptool.c, navit/maptool/maptool.h, navit/maptool/osm.c, navit/maptool/osm_relations.c
This pull request increases processing speed of maptool on large areas (world) by partly parallelizing the turn restriction processing as well as by introducing buffered read of nodes on relation processing.
Time saved on my box: -1day / ~20%
=> enhancement:maptool:improve processing speed and fix some memory holes

docs/development/android_development.rst, docs/index.rst
Migrating the following docs:
https://wiki.navit-project.org/index.php/Android_development
=> update:docs:Migrate Android development documentation over

navit/android.c, navit/search.c, navit/search.h
Closes: #898 
The only differences I can see between the function in search.c and the one in android.c are:
* the signature takes a `const char *` in android.c instead of a `char *` which shouldn't be a problem
* the 1st if of the for loop has a duplicate `ret[i] == ',' ||` condition which is cleaned up with the PR
Note that this would add a compilation warning saying:
```
warning: passing argument 1 of ‘search_fix_spaces’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
```
But as we need the const context for the android part to call `ReleaseStringUTFChars` I'm not sure if there's a better way to do that.
=> cleanup:search:Remove duplicate code for search_fix_spaces

navit/maptool/CMakeLists.txt, navit/maptool/boundaries.c, navit/maptool/buffer.c, navit/maptool/ch.c, navit/maptool/coastline.c, navit/maptool/itembin.c, navit/maptool/itembin_buffer.c, navit/maptool/itembin_slicer.c, navit/maptool/maptool.c, navit/maptool/maptool.h, navit/maptool/misc.c, navit/maptool/osm.c, navit/maptool/osm_protobuf.c, navit/maptool/osm_protobufdb.c, navit/maptool/osm_psql.c, navit/maptool/osm_relations.c, navit/maptool/osm_xml.c, navit/maptool/sourcesink.c, navit/maptool/tempfile.c, navit/maptool/tile.c, navit/maptool/zip.c
This commit allows to slice all polygons (except poly_water_sliced) into
squares so that they fit into smaller map tiles. Holes if present are
correctly sliced as well.
This has the advantage that they do not need to be processed albeit not
being displayed, and navit-planet-extractor can filter them out.
This has the disadvantage that the big polygons are displayed checkered
if the corresponding itemgra in config features an outline.
TODO: Slice already on polygon creation. Currently the slicing has to be
performed twice, because of tile preprocessing and saving is done in
seperate steps from the tempfiles.
TODO: Make the trigger for slicing configurable. Right now it slices
everything smaller than tile level 4.
Hopefully fixes #894
=> enhancement:maptool:slice big polygons into smaller parts

CHANGELOG.md, docs/conf.py, docs/development/changelog_wrapper.rst, docs/index.rst
Added Changelog to Doc to be able to reference to it, and as well have a nice integrated display even within the offline docs (pdf copy)
=> add:doc:Add Changelog to doc with Markdown include (m2r)

scripts/ci_sanity_checks.sh
The current way of doing with interval sometimes leads to the last commit from trunk being included in the diff, leading to false positives.
This change simplifies the way we pull the files, and should make it more reliable.
=> cleanup:ci:Simplify the listing of files for sanity check

.circleci/config.yml, .gitignore, scripts/setup_sanitycheck_requirements.sh
=> Move checkstyle into the sanity_check phase

.circleci/config.yml, scripts/check_need_build.sh
Closes #925 
The idea is to skip the build steps if the change is only done on `*.md` or `*.rst` files or is only in the `docs` folder.
Saves CI time and makes the time to have the relevant checks passing shorter. Should help on #910 
Note that the branch should be be up-to-date with trunk to make it work.
Side note: if there is no diff with trunk (aka that's pushed on master or trunk) then we only check for the files in the last commit).
And if we are on a tag, we just exit 1 as we want to build even if the last change is a doc change.
=> update:CI: skip the build steps if the change is only for documentation

navit/binding/dbus/binding_dbus.c, navit/font/freetype/font_freetype.c, navit/geom.c, navit/geom.h, navit/graphics/opengl/graphics_opengl.c, navit/gui/gtk/destination.c, navit/gui/gtk/gui_gtk_statusbar.c, navit/gui/internal/gui_internal.c, navit/gui/internal/gui_internal_command.c, navit/gui/internal/gui_internal_command.h, navit/gui/internal/gui_internal_html.c, navit/gui/internal/gui_internal_keyboard.c, navit/gui/internal/gui_internal_search.c, navit/gui/internal/gui_internal_widget.c, navit/gui/qml/navitProxy.h, navit/map/binfile/binfile.c, navit/map/filter/filter.c, navit/map/shapefile/shapefile.c, navit/map/textfile/textfile.c, navit/maptool/osm.c, navit/osd/core/osd_core.c, navit/roadprofile.c, navit/roadprofile.h, navit/speech/qt5_espeak/Qt5EspeakAudioOut.cpp, navit/traffic/traff_android/traffic_traff_android.c, navit/vehicle.c, navit/vehicle.h, navit/vehicleprofile.c, navit/vehicleprofile.h
This PR fixes a lot of compiler warnings. The core and the well maintained plug ins build at least under Linux without severe warnings.
=> fix:various:fix compiler warnings

checkstyle.xml, docs/development/programming_guidelines.rst, navit/android/build.gradle
In [8.24](https://checkstyle.org/releasenotes.html#Release_8.24), the following change happened:
```
Change LineLength Check parent from TreeWalker to Checker. Author: rnveach, Roman Ivanov #2116
```
In [8.25](https://checkstyle.org/releasenotes.html#Release_8.25), the following change happened:
```
JavadocMethodCheck: remove deprecated properties ignoreMethodNamesRegex, minLineCount, allowMissingJavadoc, allowMissingPropertyJavadoc. Author: rnveach #7096
```
This PR is fixing this.
Fixes #945
=> fix:ci:Fix checkstyle changes since 8.24

.circleci/config.yml
Fix android build on circleci, now using ndk version of the circleci images
tested with command: circleci local execute --job build_android
=> fix:build:android:Fix android build on circleci

.circleci/config.yml
This is just changing the default image to pull more up-to-date dependencies like gcc.
=> Update:CI: Use debian:latest in the CI to get more up-to-date tools

navit/plugin/pedestrian/pedestrian.c
In Debian, the build fails with the 2 following errors:
```
/<<PKGBUILDDIR>>/navit/plugin/pedestrian/pedestrian.c: In function ‘pedestrian_navit_init’:
/<<PKGBUILDDIR>>/navit/plugin/pedestrian/pedestrian.c:1341:12: error: too few arguments to function ‘navit_attr_iter_new’
1341 |     iter = navit_attr_iter_new();
|            ^~~~~~~~~~~~~~~~~~~
/<<PKGBUILDDIR>>/navit/plugin/pedestrian/pedestrian.c:1400:12: error: too few arguments to function ‘config_attr_iter_new’
1400 |     iter = config_attr_iter_new();
|            ^~~~~~~~~~~~~~~~~~~~
```
This PR should fix that.
Note that the following flags are set during the build. Maybe we should consider having those inside our standard build system to avoid surprises (broken in several lines for readability):
```
-fstack-protector-strong …
```
=> fix:plugins: too few arguments to functions navit_attr_iter_new and config_attr_iter_new

.circleci/config.yml
For whatever reasons the sailfish rpms are not visible in circleci
any more when they used to be. Maybe because of indirect path usage on
uploading them. This fixes that.
=> fix:ci:fix sailfish artifacts uploading

navit/maptool/osm.c
As a lot of big water dams are mapped as waterway=weir, add this tag to Navit as well.
=> add:maptool:add waterway=weir as poly_dam to map

fastlane/Fastfile, navit/android/build.gradle, scripts/setup_publish_keys.sh
This happens usually if building with CI on fork repository
may fix #994
=> fix:build:android: Don't sign apk if no valid keyring is available

navit/navit_layout_car_dark_shipped.xml, navit/navit_layout_car_shipped.xml
Improve rendering order involving park, meadow, scrub, and wood polygons.
Please see before and after below:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
=> Make sure park, meadow, scrub, and wood render in correct order

navit/navit_layout_car_dark_shipped.xml, navit/navit_layout_car_shipped.xml
Improve rendering order involving industry, sport, meadow, scrub, and cemetery polygons.
Please see before and after below:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
=> Make sure industry, sport, meadow, scrub, and cemetery render in correct order

navit/navit_layout_car_shipped.xml, navit/textures/diagonal-stripes.svg
This pull request adds a red stripe texture that is used for poly_danger_area on car layout.
Additionally to that, a lightly transparent red border is added to it.
To see the diagonal stripes one needs to use either gtk_drawing_area or qt5 graphics as only those currently support textured polygons.
=> Enhancement:layout_car:Add stripes to danger_area

navit/maptool/maptool.c, navit/maptool/osm.c
In order to support (multi)polygons that are tagged with more than one
set of tags resulting it to require two navit items to be represented on
map, affected elements are duplicated and added with every item type
decoded. This is already done for ways and points. This fix makes
maptool do this for multipolygons as well.
+ fixes some valgrind findings
=> Fix:maptool:Duplicate multipolygons if required

navit/navit_layout_car_dark_shipped.xml, navit/navit_layout_car_generatedarkxml.sh
Improve Car-Dark layout colors auto-generated by the script.
Examples:
Compare to before this PR and see the improvement:
=> Improve Car-Dark layout colors

navit/xslt/map_sdcard_navitmap_bin.xslt
Activate downloaded maps automatically on Android by including the `/sdcard/Download` directory.
This is done so that maps downloaded in the browser, f.ex. using the Planet Extractor, which go to `/sdcard/Download` by default, are activated automatically without having to change the map location in de UI. This way, maps can be downloaded in the app using the UI, and maps can also be downloaded through the browser. Both will _just work™_.
=> Android: Activate downloaded maps automatically

navit/track.c
This PR fixes a little log message which hopefully a normal user should never see, and is Probably only relevant for Developers which develop a vehicle Plugin. It just tells which attribute-date is missing.
=> fix:core:Optimize log message for required vehicle attributes

navit/vehicle/gpsd/vehicle_gpsd.c
This PR fixes the Build against Gpsd 3.21 which had introduced another api change. 
Today its the status which went from `gps_data_t->status` to `gps_data_t->fix.status` 
Changelog for this is here: https://gitlab.com/gpsd/gpsd/-/blob/00c66ad6f44f6283cdddc5f48f334216daf78f12/gps.h#L82
=> fix:vehicle:gpsd:Add Support for Gpsd 3.21

navit/command.c, navit/map/binfile/binfile.c
Fix two issues where the wrong enum type is used, but both have the same value of 0
=> fix:build:core:Fix two issues where the wrong enum type is used

navit/plugin/j1850/j1850.c
Looks like this was missed in:
46f67d8937cfef6158eeee6e5ed039d29fc1b8f7
Fixes:
```
j1850.c:319:46: error: ‘struct osd_item’ has no member named ‘graphic_fg_white’
```
=> Fix:plugin/j1850: Replace graphic_fg_white with graphic_fg.

CMakeLists.txt
Necessary for build to succeed on Ubuntu 18.04 (possibly others).
=> Fix:build:Prevent try_compile() from choking on CXX

navit/route.c
Fixes a potential crash when `route_get_selection()` is called before acquiring the first position
Correct documentation for `route_graph_build()`
=> Minor TraFF-related fixes

navit/support/espeak/readclause.c
There is a small typo in navit/support/espeak/readclause.c.
Should read `usage` rather than `useage`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, useage -> usage

checkstyle.xml
This relaxes some checkstyle rules to be in line with what we require for C code (see #1041):
* MemberName: No longer enforce member names à la `mFoobar` (which is reminiscent of a now-discouraged practice in C and which we don’t enforce or even use there); now the only requirement is that member names must start with a lowercase letter (as identifiers starting with an uppercase letter are for class names) and contain nothing other than letters and numbers. Hence any of `mFoobar`, `foobar` or `fooBar` is now accepted. `Foobar` or `foo_bar` would get flagged as before.
* NeedBraces: We don’t require braces around single-statement blocks in C (and usually omit them there), so the same now applies to Java code.
* VariableDeclarationUsageDistance: No longer enforced—in C we require variable …
=> Fix:ci:Relax checkstyle rules for Java code, see #1041

gradle/scripts/git-scm-version.gradle
Currently the VersionCode has the Format yyMMddHHmm
which breaked at 01.01.2021 because the maximum allowed Version by
Google Play is 2100000000 because of the limitation of older Android
Devices.
Out currently highest VersionCode is 2012201504 and we need to keep it
continuous, so the new Format would be yyyyMMddHH.
Of cause this has the limitation that we can "only" create one
Versioncode per Hour.
But this is the the best @hoehnp and I came up yesterday.
As a result a PR will follow which will remove the android build from
the master build and instead will add it to a scheduled build (nightly
build)
=> fix:build:android: Fix VersionCode after 31.12.2020

navit/support/gettext_intl/dcigettext.c
Fixes #1043
Holding this back while jkoan is still investigating the build issues on F-Droid.
I have successfully built this locally on NDK 21, then after downgrading to NDK 18 (which had not experienced the issue this commit intends to fix).
@jandegr I can’t officially add you as a reviewer here, but your input would be appreciated (e.g. if I’ve overlooked something).
=> Fix:build/android:do not double-define getcwd on recent NDK versions

CMakeLists.txt
This fixes issues with builds failing because of CMake not finding a suitable C++ compiler although CXX was explicitly disabled.
Sample output from an Android build, which this PR fixes:
```
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:10 (project):
No CMAKE_CXX_COMPILER could be found.
Tell CMake where to find the compiler by setting either the environment
variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
to the compiler, or to the compiler name if …
```
=> Fix:build:do not request CXX if explicitly disabled

build.gradle, scripts/build_android.sh
As described in #762, this now moves all CMake output from the Android build to a subdir named `android-builddir`.
<del>For now, generated XML, PNG and translation files still get copied into the source tree. However, each gets written to an otherwise unused subdir (no mixing of code and generated files within the same dir), making cleanup much easier than before.</del>
With this change, the Android build leaves five elements in the source tree:
* `android-builddir/` (the build dir)
* `cmake_plugin_settings.txt`
* <del>`navit/android/assets/` (XML config files, entire dir)</del>
* <del>`navit/android/res/drawable-nodpi/` (PNG bitmaps, entire dir)</del>
* <del>`navit/android/res/raw/`(translations, entire dir)</del>
@jkoan For now, this does not change anything about the use of …
=> Fix:build:Reduce source tree pollution by Android build

.circleci/config.yml, CMakeLists.txt, build.gradle
As discussed with @jkoan on IRC, this fixes the build issues we had on F-Droid (see #1085).
The issues were caused by the toolchain trying to build against host libraries, which doesn’t work when cross-compiling, as is the case for Android. Oddly, this only happened on some build environments, not on others; we never quite figured out why. On those that worked, our bundled support libraries were used. These are essentially stripped-down versions of upstream libraries which aren’t getting a lot of maintenance—a kludge we’d rather avoid having to use and are hoping to get rid of one day.
This fix ensures the correct directories are passed to CMake and pkg-config. A test run of the F-Droid build (on the F-Droid CI setup) has passed.
The changes require NDK when running `sanity_check`, …
=> Fix:build:Fix F-Droid build

.circleci/config.yml, .fdroid.yml
This adds a new CircleCI job which will build Navit in an F-Droid build environment.
The environment is identical to what F-Droid currently uses for CI. Some changes to the build recipe were necessary (see comments) as the CI image does not fully correspond to the live build server. Therefore, passing CI is no guarantee that this version will build on F-Droid (and vice versa), but it is as close as reasonably possible right now.
On the long run, we could consider dropping the Android build job and instead just signing the output of this job with our key and uploading it to Google Play. However, that is beyond the scope of the present PR.
=> Add:CI:Add job for F-Droid build

.fdroid.yml
Replicating a change requested by the F-Droid team, to keep our in-repo recipe in sync with the one on fdroiddata (as far as possible). Turns out build.xml is no longer needed, seems to be an ant leftover.
=> Refactor:fdroid:Remove build.xml generation

navit/android/src/org/navitproject/navit/Navit.java, scripts/build_android.sh
As mentioned in #1117:
* Default location for file picker is Navit’s private shared storage dir (`/sdcard/Android/data/org.navitproject.navit/files`), which is not affected by restrictions introduced with Android 11
* When the selected path contains Navit’s package ID, it is applied as-is (rather than appending `/navit`) – this is the same behavior as for paths including `/navit`, the assumption being that we are already in a Navit-specific part of the filesystem
=> Make file picker compatible with Android 11

navit/maptool/osm.c
This commit causes maptool to filter out multipolygon relations
whose tags result in unknown binfile type before processing them 
if -n is given on command line. May save a lot of processing time.
=> fix:maptool: filter out unknown multipolygons before processing

navit/maptool/osm.c
Change done at #1129 causes maptool to filter out all multipolygons
if -n is given due to not correctly initializing item_bin buffer
prior check. Sorry my fault.
=> Fix:maptool:osm fix multipolygon filter.

navit/maptool/itembin.c
The removed assertion disallowed the use of item_bin_copy_attr for
anything else than attr_osm_wayid when debug build was enabled. This
used to work prior the introduction of multipolygon support. There
item_bin_copy_attr is used to copy all kinds of attrs not knowing about
the assert.
So remove the assert as it seems to have been never correct.
Fixes #1147
=> FIX:maptool: remove assertion from item_bin_copy_attr

navit/graphics/qt5/QNavitQuick.cpp, navit/graphics/qt5/QNavitWidget.cpp, navit/navit.c
This commit causes navit to cancel async drawing in case of resize
request. Drawing is started again after that. this should effectively
cause a redraw on subsequent calls to resize. Some graphics like qt5
call resize for both dimension changes if the widget gets resized.
=> Fix:core: cancel drawing on resize request

navit/gui/gtk/gui_gtk_action.c
GTK gui uses the same icon for destination and poi dialog. 
Use GTK_STOCK_INFO icon for poi dialog.
=> Unique icon for POI dialog

CMakeLists.txt, navit/graphics/qt5/graphics_qt5.cpp
As building qithout QML is rarely done, a ifdefing mistake was made in graphics qt5. This change requests fixes this.
Additionally gui_qt5_qml is disabled when QML support is disabled on graphics_qt5 as this is mandatory.
=> Fix:graphics_qt5: allow building without qml again

navit/maptool/osm.c
Cleans up place to area processing
=> fix:maptool: Don't drop unrecognized relations to borders temp file

navit/maptool/osm_xml.c
Deny \<tag k=... v=..\> processing before first <node> element is read.
Let maptool silently skip boundary and changeset  elements.
=> fix:maptool:skip changeset elements and their tags in the osm xml file.

docs/development/linux_development.rst
Added missing dependency libspeechd-dev for Raspberry Pi OS.
=> Fix linux_development.rst

.circleci/config.yml
See #1203. This reverts to an earlier version of F-Droid server, compatible with the Debian version on the CI image.
=> Fix:ci:use F-Droid server version compatible with OS image

navit/android/src/org/navitproject/navit/NavitVehicle.java
Android’s fused location provider aggregates locations from multiple providers, typically network and gps.
The AOSP version seems to indiscriminately pipe through any location updates it gets from the backend providers, with no verification or filtering.
When your references are a precise GPS signal and a network location based on a cell tower, with several hundred meters of error, this may cause your position to jump wildly between two places and navigation will become unusable. Such behavior would be OK for the ”fast” provider (which establishes your initial position and gets disabled as soon as the first location from the precise provider is received), but not for the precise provider (which would normally be used for navigation).
Unfortunately, Android seems to prefer the fused …
=> Fix:vehicle/android:Never use fused provider for precise location

.circleci/config.yml
As recommended by F-Droid. this switches to the `fdroidserver:buildserver` image (maintenance for the image we used so far is going to be discontinued in the near future, and recent changes to F-Droid’s build infrastructure already require a hack in order for this image to work).
For the moment, we are just switching to `fdroidserver:buildserver-stretch`, which was the current version until a week ago. Migration to `fdroidserver:buildserver-bullseye`, now the current version, is underway but there are still some rough edges to work out. This PR gets us one step closer while keeping our CI running.
=> Add:ci:Use fdroidserver:buildserver image for build_fdroid

.circleci/config.yml, .fdroid.yml
See #1203.
This updates our CI to the latest image used by F-Droid, based on Debian bullseye.
WIP because of one open question: **is `libgtk2.0-dev` needed when building for Android?** The build completes without it, but I haven’t tried out the resulting APK.
As soon as someone can confirm that building without `libgtk2.0-dev` will not affect the Android APK, this can be merged as far as I am concerned.
=> Add:ci:Update F-Droid CI to Debian bullseye

navit/coord.c, navit/gui/internal/gui_internal.c, navit/gui/internal/gui_internal_command.c
This PR extends the geo coordinates format accepted by the internal GUI.
A new valid format is accepted like 52.5219,19.4127 (decimal latitude and longitude separated by a comma character, without any space).
This allows inputting locations like they are displayed within Google maps:
=> Add:gui/internal: Allowing comma-separated geo coordinates

navit/maptool/osm.c
Use attr_none as we are handling an attribute type and not an item type.
=> Fix: Warning during build

navit/util.c
This fixes the issue #1179. Tested with testcases and working until Y2K38 by when we would need long values to be used.
=> Fix: #1179

navit/script/osm/border_follower.pl, navit/script/osm/osmtool.pl
Use `api.openstreetmap.org/api/` -and HTTPS- instead of `www.openstreetmap.org/api/*`.
(Is: https://github.com/openstreetmap/operations/issues/951)
You will likely need to update code parameter `APIClientV5` and related file/package, and url parameter `0.5` => `0.6`, if in-use.
(Also, sorry for default 'updated file ...' commit message.)
cc: @OLFDB
=> Switch to api.openstreetmap.org API host

.circleci/config.yml, CMakeLists.txt, contrib/sailfish/navit-sailfish.spec, contrib/ubuntutouch/.gitignore, contrib/ubuntutouch/CMakeLists.txt, contrib/ubuntutouch/clickable.yaml, contrib/ubuntutouch/manifest.json.in, contrib/ubuntutouch/navit.apparmor, contrib/ubuntutouch/navit.desktop, gradle/scripts/git-scm-version.gradle, navit/binding/python/CMakeLists.txt, navit/bookmarks.c, navit/callback.c, navit/coord.c, navit/debug.c, navit/graphics/qt5/CMakeLists.txt, navit/graphics/qt5/graphics_qt5.cpp, navit/graphics/qt5/graphics_qt5.qml, navit/graphics/qt5/graphics_qt5.qrc, navit/graphics/qt5/loader_norotate.qml, navit/graphics/qt5/loader_norotate_ubtouch.qml, navit/support/glib/fake.c, navit/support/glib/fake.h, navit/vehicle/qt5/vehicle_qt5.cpp, navit/xslt/ubtouch_mapset.xslt, navit/xslt/ubtouch_qt5.xslt, scripts/setup_android.sh
This PR does add build files to build a Click package for UBPorts Ubuntu Touch. It is mainly based on the previous work for Sailfish Os,
Additionally this PR fixes coordinates from string parsing.
Additionally this PR fixes the current Android build by selecting ruby gems by specific version during CI.
=> os:ubuntutouch: Add build files for Ubuntu Touch clickable package
