navit-gps/navit

circle.yml
navit/android/AndroidManifest.xml.cmake
navit/android/AndroidManifest.xml.in
navit/android/src/org/navitproject/navit/NavitGraphics.java
navit/navigation.c
navit/navit_shipped.xml

PR to merge Jan's latest changes in the trunk

H5 followup

---

navit/navigation.c

see routing QA NAV_Antwerpen and NAV_Budapest and the IRC log 2015-09-29
for the report of the Budapest case by tparcina

some missing maneuvers

---

navit/navigation.c

reduce map read in navigation.c

---

navit/navigation.c

Refactor:core:Clean up code and comments in navigation.c, see #1274

---

navit/android/src/org/navitproject/navit/NavitGraphics.java

Fix:port/android:Handle up/down keys correctly, fixes #1252

---

ci/build_android.sh
circle.yml
navit/android/src/org/navitproject/navit/Navit.java

removes titlebar on Android 2.x devices
allows the removal of the actionbar on Android >= 3 devices by means of the fullscreen function
bump SDK
disable maptool in the Android build

trac #1325 actionbar and titlebar

---

navit/projection.h

Refactor:core:Document projections

---

navit/route.c

Refactor:core:Add/improve documentation in route.c

---

navit/command.c
navit/osd.c

Fixes issue with initial OSD enable_expression evaluation

Merge:Trac1334

---

navit/gui/internal/gui_internal_command.c

Fix:gui_internal:Format coordinates properly on Android Lollipop

---

navit/gui/internal/gui_internal.c
navit/gui/internal/gui_internal_command.c
navit/gui/internal/gui_internal_widget.c

Refactor:gui_internal:Some documentation updates

---

navit/gui/internal/gui_internal.c
navit/gui/internal/gui_internal_keyboard.c

Refactor:gui_internal:Documentation update

---

navit/gui/internal/gui_internal_keyboard.c
navit/gui/internal/gui_internal_priv.h
navit/gui/internal/gui_internal_widget.c

Refactor:gui_internal:More documentation

---

navit/gui/internal/gui_internal_bookmark.c
navit/gui/internal/gui_internal_command.c
navit/gui/internal/gui_internal_html.c
navit/gui/internal/gui_internal_keyboard.c
navit/gui/internal/gui_internal_keyboard.h
navit/gui/internal/gui_internal_poi.c
navit/gui/internal/gui_internal_search.c

Refactor:osd_internal:Use enum for keyboard modes and flags

---

ci/build_android.sh
circle.yml

cleanup the scripts for the Android-build, 
but incomplete, there is more to clean-up

Android build cleanup

---

navit/android/src/org/navitproject/navit/Navit.java
navit/android/src/org/navitproject/navit/NavitGraphics.java
navit/attr_def.h
navit/graphics/android/graphics_android.c
navit/osd/core/osd_core.c
navit/xpm/Makefile.am
navit/xpm/gui_android_menu.svg
navit/xslt/android.xslt
navit/xslt/osd_android.xslt
navit/xslt/osd_minimum.xslt

See http://trac.navit-project.org/ticket/1325. If there are no objections I will merge it in the next days.

Add:port_android:OSD button to show Android menu

---

navit/android/src/org/navitproject/navit/Navit.java
navit/android/src/org/navitproject/navit/NavitGraphics.java
navit/graphics.c
navit/graphics.h
navit/graphics/android/graphics_android.c
navit/graphics/gd/graphics_gd.c
navit/graphics/gtk_drawing_area/graphics_gtk_drawing_area.c
navit/graphics/null/graphics_null.c
navit/graphics/opengl/graphics_opengl.c
navit/graphics/qt_qpainter/graphics_qt_qpainter.cpp
navit/graphics/sdl/graphics_sdl.c
navit/graphics/win32/graphics_win32.c
navit/gui/internal/gui_internal.c
navit/gui/internal/gui_internal_bookmark.c
navit/gui/internal/gui_internal_command.c
navit/gui/internal/gui_internal_html.c
navit/gui/internal/gui_internal_keyboard.c
navit/gui/internal/gui_internal_keyboard.h
navit/gui/internal/gui_internal_poi.c
navit/gui/internal/gui_internal_search.c

Rebased as discussed with sleske, replaces #47

Add:gui_internal:Support native on-screen keyboard (currently Android only)

---

navit/maptool/osm.c

navigation.c contains code to handle destination: backward and forward, but the changes needed in maptool to provide those did not get merged yet.

add destination forward/backward

---

navit/navit.c

A wider usage version of the layout switch command in https://github.com/navit-gps/navit/pull/83
sample usage as a command in navit.xml 
command="switch_layout_day_night(&quot;manual_day&quot;)"
see the code for more usage cases

Layoutswitcher

---

po/de.po.in

Automatic translation import

---

navit/gui/internal/gui_internal_command.c

some fixes for the heightprofile in gui internal.
the name of the map with heightlines must be 
*.heightlines.bin

Gui internal heightprofile

---

navit/navit_shipped.xml
navit/xpm/gui_layers.svg

As the title says, add a menu entry settings->display->layers to change layer visibility and an icon for it.

Gui internal layercontrol

---

po/zh_TW.po.in

Update:i18n:Updated Chinese (Traditional) translation from launchpad

Automatic Chinese (Traditional) translation import

---

po/af.po.in

Update:i18n:Updated Afrikaans translation from launchpad

Update:i18n:Updated Afrikaans translation from launchpad

---

ci/build_android.sh
ci/build_android_x86.sh
ci/build_tomtom_minimal.sh
ci/build_tomtom_plugin.sh
circle.yml

Reduces the differences between android-arm and android-x86 builds.
Ideally we might have only one script with just different parameters soon.
Also bumped libpng for the tomtom build as it was breaking the build. In a future PR we'll have to find a better way to handle the tomtom builds dependencies

Android ci optimization

---

ci/build_linux.sh
ci/build_tomtom_minimal.sh
ci/build_tomtom_plugin.sh
ci/run_linux_tests.sh
circle.yml

Ensures that the tests are run on the same container as the linux build.

Fix:CI:Improved linux tests

---

contrib/tomtom/espeakdsp.c

let espeakdsp don't send more bytes then received.
This solve the noise problem speaking empty strings

fix buffer usage

---

navit/map/binfile/binfile.c

a tweak in binfile.c so a gui can be made to search for attr_town_postal in a similar way as a search is done for attr_town_or_district_name.

Postcodesearch_essentials

---

navit/graphics/qt5/QNavitQuick.cpp
navit/graphics/qt5/QNavitWidget.cpp
navit/graphics/qt5/QNavitWidget.h
navit/graphics/qt5/graphics_qt5.cpp
navit/graphics/qt5/graphics_qt5.qml

This pull request adds keyboard input for graphics_qt5 plugin

graphics Qt5 keyboard

---

navit/osd/core/osd_core.c

Fixes [trac981](http://trac.navit-project.org/ticket/981)

Fix trac981: Add Align-Attr to osd type Odometer

---

navit/osd/core/osd_core.c

This PR shall fix [trac-1246](http://trac.navit-project.org/ticket/1246)

Trac-1246: Draw background color even if text label is empty.

---

navit/graphics/qt5/QNavitQuick.cpp
navit/graphics/qt5/QNavitQuick.h
navit/graphics/qt5/QNavitWidget.cpp
navit/graphics/qt5/QNavitWidget.h
navit/graphics/qt5/event_qt5.cpp
navit/graphics/qt5/event_qt5.h
navit/graphics/qt5/graphics_qt5.cpp
navit/graphics/qt5/graphics_qt5.h
navit/vehicle/qt5/vehicle_qt5.cpp
navit/vehicle/qt5/vehicle_qt5.h

* Apply coding style (using clang-format) to graphics qt5 and vehicle qt5
* Fix includes
* Fix file header copyright notes

Refactor: graphics_qt5 and vehicle_qt5 cleanup

---

navit/navit_shipped.xml

Should fix flooding issue as mentioned by @jandegr in https://github.com/navit-gps/navit/pull/240#issuecomment-299688542.

Revert: move poly_water_tiled in Car layout

---

navit/navit_shipped.xml

https://github.com/navit-gps/navit/pull/240#issuecomment-299689298

Add poly_basin

---

navit/navit_shipped.xml

https://www.openstreetmap.org/#map=19/52.95293/6.30800

Add feature poly_reservoir

---

contrib/sailfish/navit-sailfish.spec
navit/graphics/qt5/CMakeLists.txt
navit/graphics/qt5/graphics_qt5.cpp
navit/graphics/qt5/graphics_qt5.h

Fix native Qt5 font support to get rid of mandatory freetype dependency.

Fix: Qt5 fonts

---

navit/graphics/qt5/QNavitQuick.cpp
navit/graphics/qt5/QNavitWidget.cpp
navit/graphics/qt5/graphics_qt5.cpp
navit/graphics/qt5/graphics_qt5.h

This pull request enables the draw_drag api for grapics_qt5. This allows to set drag_bitmap=1 in navit.xml

Correctly implement draw_drag on graphics_qt5

---

navit/graphics/qt5/QNavitWidget.cpp
navit/graphics/qt5/graphics_qt5.cpp

Now cursor is drawn right with qml and qwidgets

fix: graphics_qt5 fix layer drawing and dragging

---

ci/build_android.sh
ci/build_android_x86.sh
ci/build_linux.sh
ci/build_tomtom_minimal.sh
ci/build_tomtom_plugin.sh
ci/build_win32.sh

Ci has 32 Cores, not 4 Which is reportet from nproc.
So build should be faster ;)

Use all available Cores for Ci

---

navit/navit_shipped.xml

Use Car-Android cursor as default cursor in Car and Car-dark layouts. Changed the green color to blue for the Car-dark layout.

Change default cursor in Car and Car-dark layouts

---

navit/support/shapefile/dbfopen.c
navit/support/shapefile/shapefil.h
navit/support/shapefile/shpopen.c
navit/support/shapefile/shptree.c

Comes with a brand new documentation about how to use Shapefiles with Navit : https://wiki.navit-project.org/index.php/Shapefiles

Updated shapefile driver

---

ci/build_tomtom_minimal.sh
ci/build_tomtom_plugin.sh
navit/gui/internal/gui_internal_command.c

@zintor can you please confirm that it fixes your issue?

Fixes displaying the heightline route info

---

.circleci/config.yml
ci/build_linux.sh
ci/build_tomtom_minimal.sh
ci/build_tomtom_plugin.sh
ci/docker/tomtom/Dockerfile
ci/docker/tomtom/README.md
ci/docker/tomtom/entrypoint.sh
ci/docker/tomtom/tomtom.cache

Update coverity tools to 2017.07 and adapt the relevant script to circleci v2

Coverity upgrade

---

navit/icons/autoservice.svg

this PR adds a missing icon for autoservice

autoservice

---

navit/icons/drinking_water.svg

add drinking_water.svg designed by me - free to use

add:icon:drinking_water

---

navit/icons/diving.svg

add diving.svg designed by me - free to use

add:icon:diving

---

.circleci/config.yml
navit/Doxyfile

This way it's available on http://navit-gps.github.io/navit/ and the doxygen.navit-project.org can be used there.

Build doxygen doc and push the result to a gh-pages branch

---

navit/icons/diving.svg

Icon diving

---

navit/icons/hotspring.svg

add icons designed by me - free to use

add:icon:hotspring

---

navit/gui/gtk/gui_gtk_action.c

Added the ability to toggle whether navit follows the active vehicle on its display to the Display menu.

Gtk add follow vehicle toggle

---

navit/icons/emergency.svg

add emergency.svg designed by me - free to use

add emergency.svg designed by me - free to use

---

navit/icons/bridge.svg

Icon bridge

---

navit/icons/bowling.svg

Icon bowling

---

navit/icons/ghost_town.svg

add ghost_town.svg designed by me - free to use

add:icon:ghost_town

---

navit/icons/fish.svg

add fish.svg designed by me - free to use

add:icon:fish

---

navit/gui/gtk/gui_gtk_statusbar.c
navit/navigation.h
navit/navit.c
navit/vehicle/gpsd/vehicle_gpsd.c

* Some new conversion factors in navigation.h.
* Corrected conversions to to use the correct factors.
* Got rid of a hard coded value, replaced it with a #define.

fix:gtk:Fix imperial factors

---

navit/icons/navit_svg2png

To know how to use the script you had to inspect the script code.
Error messages and help/usage messages added.

Add:doc:added errors and usage messages to navit_svg2png script

---

navit/route.c
navit/util.c

Refactor:route:Improve documentation

---

navit/Doxyfile
navit/plugin.c
navit/vehicle.c
navit/vehicle/android/vehicle_android.c
navit/vehicle/demo/vehicle_demo.c
navit/vehicle/file/vehicle_file.c
navit/vehicle/gpsd/vehicle_gpsd.c
navit/vehicle/gpsd_dbus/vehicle_gpsd_dbus.c
navit/vehicle/gypsy/vehicle_gypsy.c
navit/vehicle/iphone/vehicle_iphone.c
navit/vehicle/maemo/vehicle_maemo.c
navit/vehicle/null/vehicle_null.c
navit/vehicle/qt5/vehicle_qt5.cpp
navit/vehicle/webos/vehicle_webos.c
navit/vehicle/wince/vehicle_wince.c

This PR add Documentation to the Plugins and the Plugin Sytem.
Also all support libraries are excluded to keep focus on navit and because they are not navit related.

Add some Documentation to Plugins

---

navit/gui/gtk/gui_gtk_statusbar.c
navit/navigation.c
navit/navigation.h
navit/navit.c

Another go at fixing imperial measures. This is ready for testing on a different machine, but not for a pull request.
Also, some improvements in some comments.
OK, after 210 miles of tests, I think it's ready for prime time.

fix:gtk:Fix imperial factors. Again.

---

navit/route.c

Refactor:route:More documentation

---

navit/item.c
navit/map.h

Refactor:core:Add more documentation

---

ci/build_linux.sh

So that the CircleCI Build does not fail because of "10min without any output"

fix:build:Fix download of Cov

---

.circleci/config.yml
ci/update_doxygen.sh

Move the actual code of the update Script into a own file to clean up the circleci config file.

change:build:Move update of doxygen to own script

---

.circleci/config.yml
ci/build_linux.sh
ci/setup_common_requirements.sh
ci/update_download_center.sh

This PR adds the upload to the new download center to circleci.
To get meaningfull results two things are missing:
- Jekyll Theme for the download center [download-center#1](https://github.com/navit-gps/download-center/issues/1)
- Finish work on #309 
But both things does not prevent the PR to be merged.
The goal is to have a auto updating download page with good UX for endusers to download navit.
This PR is only the first step to achive this.

add:build:Add download center

---

navit/attr.c
navit/binding/dbus/binding_dbus.c

Refactor:core:Some doxygen additions and corrections

---

.circleci/config.yml
ci/build_wince.sh

This implement #409 in a different way.
Example result : https://5399-30791823-gh.circle-artifacts.com/0/root/project/wince/output/navit.zip
Content of the resulting zip :
```
$ unzip -l navit.zip 
Archive:  navit.zip
Length      Date    Time    Name
---------  ---------- -----   ----
0  03-11-2018 14:41   locale/
0  03-11-2018 14:41   locale/sv/
0  03-11-2018 14:41   locale/sv/LC_MESSAGES/
20473  03-11-2018 14:41   locale/sv/LC_MESSAGES/navit.mo
0  03-11-2018 14:41   locale/jv/
0  03-11-2018 14:41   locale/jv/LC_MESSAGES/
5866  03-11-2018 14:41   locale/jv/LC_MESSAGES/navit.mo
0  03-11-2018 14:41   locale/ko/
0  03-11-2018 14:41   locale/ko/LC_MESSAGES/
15516  03-11-2018 14:41   locale/ko/LC_MESSAGES/navit.mo
0  03-11-2018 14:41   locale/lt/
0  03-11-2018 14:41   locale/lt/LC_MESSAGES/ …
```

 Update:CI:also produce a zipfile for wince builds 

---

README.md
navit/android/android_layout_default_new.xml
navit/command.c
navit/gui/internal/gui_internal.c
navit/icons/forbidden_area.svg
navit/icons/government_building.svg
navit/linguistics.c
navit/map/csv/csv.c
navit/map/garmin/garmintypes.txt
navit/navit_shipped.xml
navit/script/osm/Geo/OSM/Planet.pm
navit/vehicle/file/vehicle_file.c

See the different commit for each typo.
Pretty basic change.

Fix various mispells

---

ci/build_linux.sh

* fixed source url for the tools
* removed running make package via cov-int

Fix coverity builds

---

navit/map/garmin/garmintypes.txt
navit/navit_shipped.xml

icons: fix typo business not bussines

---

navit/android/src/org/navitproject/navit/NavitVehicle.java

Prevent a crash on Android when permission location has not been given or is revoked.

Android permission

---

CONTRIBUTING.md

That would increase the visibility on our wiki.

Add:github: Add a contributing.md that references our wiki

---

.circleci/config.yml

To fix https://circleci.com/gh/navit-gps/navit/6064

Fix:CI:Put merge-to-master in the build workflow to use requires

---

ci/build_wince.sh
navit/gui/internal/gui_internal_command.c

Closes: #455
1st run should fail on wince, then I'll work on the underlying issue.

Fix:CI:Make sure the wince build fails when make or cmake fail

---

navit/icons/gui_map.svg

Fix:icons:Remove links to unknown image from gui_map.svg

---

navit/android/src/org/navitproject/navit/Navit.java

This fixes #443 
Left Picture is the new one

fix:android:Fix for the permissions dialog

---

.circleci/config.yml
ci/publish.sh
ci/setup_android.sh

This PR fixes automated uploads to playstore from trunk.
Tested in https://circleci.com/gh/navit-gps/navit/6401

Fix:CI:Automated upload to playstore

---

navit/debug.c
navit/geom.c
navit/graphics.c
navit/map/garmin/garmin.c
navit/map/mg/block.c
navit/map/mg/street.c
navit/map/mg/town.c
navit/maptool/boundaries.c
navit/maptool/ch.c
navit/maptool/coastline.c
navit/maptool/itembin.c
navit/maptool/osm.c
navit/maptool/osm_protobuf.c
navit/maptool/osm_protobufdb.c
navit/maptool/tile.c
navit/navigation.c
navit/route.c
navit/speech/cmdline/speech_cmdline.c
navit/track.c
navit/vehicle/null/vehicle_null.c
navit/vehicle/webos/bluetooth.c

This PR removes some sections of code unreachable because in a:
```C
#if 0
...
#endif
```
block.
Note that I didn't remove the blocks that were having complete functions or the ones that seemed to be notes for later improvements.

cleanup:global:Cleanup some unreachable code

---

navit/android/src/org/navitproject/navit/Navit.java
navit/android/src/org/navitproject/navit/NavitAppConfig.java
navit/android/src/org/navitproject/navit/NavitDialogs.java
navit/android/src/org/navitproject/navit/NavitDownloadSelectMapActivity.java
navit/android/src/org/navitproject/navit/NavitGraphics.java
navit/android/src/org/navitproject/navit/NavitMap.java
navit/android/src/org/navitproject/navit/NavitMapDownloader.java
navit/android/src/org/navitproject/navit/NavitSpeech2.java
navit/android/src/org/navitproject/navit/NavitVehicle.java

Some refactoring for Android
- narrow down acces modifiers
- remove useless imports
- remove unused vars
- remove redundant vars
- fix som static access issue preventing instanrun
Done with the help of Androidstudio

refactor:Android

---

navit/android/src/org/navitproject/navit/NavitGraphics.java

This fixes an Android Lint error in Androidgraphics.java.
(call required a higher API than minSDK)
AFAIK this was the last one and opens the way to add Lint error checking in the Gradle build.

Android:Fix:graphics

---

.circleci/config.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties
navit/android/build.gradle
navit/android/navit_checkstyle.xml
navit/android/src/org/navitproject/navit/Navit.java
navit/android/src/org/navitproject/navit/NavitActivityResult.java
navit/android/src/org/navitproject/navit/NavitAddressSearchActivity.java
navit/android/src/org/navitproject/navit/NavitAppConfig.java
navit/android/src/org/navitproject/navit/NavitCamera.java
navit/android/src/org/navitproject/navit/NavitDialogs.java
navit/android/src/org/navitproject/navit/NavitDownloadSelectMapActivity.java
navit/android/src/org/navitproject/navit/NavitGraphics.java
navit/android/src/org/navitproject/navit/NavitMapDownloader.java
navit/android/src/org/navitproject/navit/NavitSensors.java
navit/android/src/org/navitproject/navit/NavitVehicle.java
navit/android/src/org/navitproject/navit/NavitWatch.java

Adds checkstyle and javadoc.
Awaiting https://github.com/navit-gps/navit/pull/569 it treats **Array brackets at illegal position** and incorrect **lexicographycal order of imports** as errors, just to start with something easy, and leaves the rest as warning.
To be refined after https://github.com/navit-gps/navit/pull/569.
adds
https://8419-30791823-gh.circle-artifacts.com/0/reports/checkstyleMain.html
https://8419-30791823-gh.circle-artifacts.com/0/doc/index.html
to what we already had (Lint)
https://8419-30791823-gh.circle-artifacts.com/0/reports/lint-results.html

Add:Android:checkstyle-javadoc

---

navit/icons/desktop_icons/navit.desktop.in

Adding a `Keywords` field in desktop file as described in:
* https://wiki.gnome.org/Initiatives/GnomeGoals/DesktopFileKeywords
* https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html

add:desktop:Add keywords to application desktop file

---

README.md

Add codefactor.io to Readme since it is used now and has good hints ;)

add:doc:addcodefactor.io

---

contrib/sailfish/build_on_sailfish_sdk.sh
navit/android/change_xslt.sh
navit/script/cabify.sh
navit/startonce.sh
navit/tools/cleanattr.sh
scripts/generate_contributors.sh
scripts/import_translations.sh
scripts/merge_i18n_update.sh
scripts/xdotools.sh

Fixes: https://www.codefactor.io/repository/github/navit-gps/navit/issues?category=Maintainability&groupId=1668

cleanup:scripts:Use $(..) instead of legacy `..` to make codefactor happy

---

navit/tools/latlon2bookmark/Makefile
navit/tools/latlon2bookmark/latlon2bookmark.c

This PR Fixes two minor Bugs wit latlon2bookmark. Now its possible to compile it again

Fix latlon2bookmark

---

navit/script/mapExtract.class.php
navit/script/mapextract.php

Not even sure we still use this script but it seems a little cleanup would make codefactor happy, so here it is.
Does anyone know how it's used?

cleanup:scripts:Fix condefactor complains "String concat is not required here; use a single string instead"

---

navit/gui/gtk/gui_gtk_poi.c

fix:gtk:poi Distances to POIs can now be shown in feet.

Curley distance poi

---

.circleci/config.yml

Just update this to have cmake 3.2 since circular issue : fixing build need improve cmake, fixing cmake need to update build :)

Add:circleci:Upgrade tomtom build image

---

navit/callback.c

Just saw that while reading the code. Cosmetic change.

cosmetic:core:Reformat callback.c to fit our standards

---

navit/coord.c

 cleanup:coord:Make sure we use g_* for malloc/free/strncpy

---

build.gradle

This fixes the issue #703 
Its because the remote servers changed there files, now its working again

Android build fix

---

scripts/build_win32.sh

As discussed on IRC we should get rid of nixpaste and clean the build up. 
I also set "set -e" to fail whatever is not working as expected.

Remove unnecessary if else constructs and nixpaste

---

navit/traffic.c
navit/transform.c

Improvements to the algorithm which matches traffic locations to their corresponding map segments. In particular, this improves match quality on mountain pass roads.

Traffic: Improve segment matching

---

scripts/build_linux.sh

Add:scripts:Make linux build script more verbose

---

navit/vehicle/qt5/vehicle_qt5.cpp

This fixes the position status update of vehicle_qt5.
Now the fix status can be properly tracked for things like OSD and auto zoom to work.

Fix:vehicle_qt5:Properly update position status

---

navit/gui/internal/gui_internal_keyboard.c
navit/gui/internal/gui_internal_keyboard.h

Add:gui/internal: Greek keyboard

Add:gui/internal: Greek keyboard

---

COPYING

We haven't opened that file in a while it seems!

Fixed typos

---

.circleci/config.yml

ändrad:        .circleci/config.yml
ändrad:        contrib/sailfish/build_sailfish_ci.sh
Thanks for contributing to Navit!
Before opening a pull request on navit, make sure your commit message follows our guidelines:
https://navit.readthedocs.io/en/trunk/development/commit_guidelines.html
and that your code is compliant with out coding style guidelines:
https://navit.readthedocs.io/en/trunk/development/programming_guidelines.html

update building of sailfish OS to version 3.1.0.12

---

navit/graphics/win32/graphics_win32.c

Add drawing polygons with holes to windows graphics except CE.

Add:graphics/windows: draw polygon with holes

---

navit/graphics/sdl/graphics_sdl.c
navit/graphics/sdl/raster.c
navit/graphics/sdl/raster.h

Add polygon with holes support to SDL graphics.

Add:graphics/sdl: Polygon with holes support.

---

navit/graphics/win32/graphics_win32.c

Add polygon with holes support for windows CE

Add:graphics/windows: polygons with holes for windows CE

---

po/de.po.in

finished German translation, thanks also to @jkoan for helping

Update:i18n:Updated German translation from launchpad

---

navit/traffic.c

Fix:traffic:Use correct coord count for restored items, fixes #900

---

navit/traffic.c

Fixes an incorrect comparison operator

Fix:traffic:Determine item delay correctly

---

navit/android/build.gradle
navit/android/res/values-v19/styles.xml
navit/android/res/values-v21/styles.xml
navit/android/src/org/navitproject/navit/Navit.java
navit/android/src/org/navitproject/navit/NavitCamera.java
navit/android/src/org/navitproject/navit/NavitGraphics.java
navit/android/src/org/navitproject/navit/NavitSensors.java
navit/graphics/android/graphics_android.c
navit/plugin/pedestrian/pedestrian.c

Fixes system bars losing transparency while dragging the map, a todo leftover from https://github.com/navit-gps/navit/pull/877, and a bit of cleanup for the pedestrian plugin.

Fix:Android:system bars 

---

po/cy.po.in

This is part of an effort to automate this process a bit further.
The version code is wrong but will be fixed in a future PR

Update:i18n:Updated Welsh translation from launchpad

---

navit/attr.c
navit/attr.h
navit/binding/dbus/binding_dbus.c
navit/bookmarks.c
navit/config_.c
navit/config_.h
navit/coord.c
navit/debug.c
navit/file.c
navit/gui/gtk/gui_gtk_action.c
navit/gui/gtk/gui_gtk_window.c
navit/gui/internal/gui_internal_command.c
navit/gui/qt5_qml/backend.cpp
navit/layout.c
navit/layout.h
navit/log.c
navit/main.c
navit/mapset.c
navit/mapset.h
navit/maptool/maptool.c
navit/navigation.c
navit/navit.c
navit/navit.h
navit/plugin.c
navit/plugin.h
navit/popup.c
navit/route.c
navit/traffic.c
navit/xmlconfig.c
navit/xmlconfig.h

This pull request tries to solve most compiler warnings. Specially the nasty ones about wrong function pointer casts.

fix:all:fix compiler warnings

---

po/de_CH.po.in

This is part of an effort to automate this process a bit further.
The version code is wrong but will be fixed in a future PR

Update:i18n:Updated German (Switzerland) translation from launchpad

---

po/da.po.in

This is part of an effort to automate this process a bit further.
The version code is wrong but will be fixed in a future PR

Update:i18n:Updated Danish translation from launchpad

---

po/ckb.po.in

This is part of an effort to automate this process a bit further.
The version code is wrong but will be fixed in a future PR

Update:i18n:Updated Kurdish (Sorani) translation from launchpad

---

po/sv.po.in

Thanks for contributing to Navit!
Before opening a pull request on navit, make sure your commit message follows our guidelines:
https://navit.readthedocs.io/en/trunk/development/commit_guidelines.html
and that your code is compliant with out coding style guidelines:
https://navit.readthedocs.io/en/trunk/development/programming_guidelines.html

Update:i18n:Updated Swedish translation from launchpad

---

docs/development/programming_guidelines.rst

I believe this is the last step for #725 
@metalstrolch does that answer your questions about the style checks?

add:doc:document the sanity check steps and add a note about the Java code

---

AUTHORS
CHANGELOG.md

Updating the changelog for the coming release.
This also update the contributors list based on our release process described in https://wiki.navit-project.org/index.php/Release_process

Prepare changelog for release 0.5.4

---

navit/android/src/org/navitproject/navit/NavitGraphics.java
navit/graphics/android/graphics_android.c

Fix: graphics/android: polygons with hole drawing

---

navit/gui/qml/navitProxy.h
navit/gui/qml/vehicleProxy.h

This fix should fix issue #980 where we have issues building gui:qml. The build is already tested with docker manually because our CI currently doesn't build qml.

Fix QML build

---

navit/navit_layout_car_convertrgbfordark.sh
navit/navit_layout_car_dark_shipped.xml
navit/navit_layout_car_shipped.xml

Visual improvements to `navit_layout_car_shipped.xml` layout, mainly tweaked colors for some polygons. Also applied the same (tinted) changes to `navit_layout_car_dark_shipped.xml` for consistency.

Improve layout

---

navit/graphics/gtk_drawing_area/graphics_gtk_drawing_area.c
navit/gui/gtk/datawindow.c
navit/gui/gtk/gui_gtk_window.c

https://developer.gnome.org/gtk3/stable/gtk-migrating-2-to-3.html
Signed-off-by: David Heidelberg <david@ixit.cz>
Thanks for contributing to Navit!
Before opening a pull request on navit, make sure your commit message follows our guidelines:
https://navit.readthedocs.io/en/trunk/development/commit_guidelines.html
and that your code is compliant with out coding style guidelines:
https://navit.readthedocs.io/en/trunk/development/programming_guidelines.html

Refactoring:GTK: use GDK_KEY for keys instead of GDK_

---

navit/navit_layout_car_dark_shipped.xml
navit/navit_layout_car_shipped.xml

Order Parking (can be covered by Meadow, Wood) and Playground (can cover Meadow)

Order Parking (can be covered by Meadow, Wood) and Playground (can cover Meadow)

---

navit/navit_layout_car_convertrgbfordark.sh
navit/navit_layout_car_dark_shipped.xml
navit/navit_layout_car_shipped.xml

Small color tweaks and added polylines

Small color tweaks and added polylines

---

navit/navit_layout_car_convertrgbfordark.sh
navit/navit_layout_car_dark_shipped.xml
navit/navit_layout_car_generatedarkxml.sh
navit/navit_layout_car_shipped.xml

Improve Car Dark layout polygon colors, bring up to date with Car Light polys, automate changes with script

Improve Car Dark layout polygon colors, bring up to date with Car Light polys, automate changes with script

---

navit/navit_layout_car_dark_shipped.xml
navit/navit_layout_car_generatedarkxml.sh
navit/navit_layout_car_shipped.xml

Improve Car Dark layout colors, bring all layers up to date with Car Light, automate changes in all layers with script
@metalstrolch OK, let's do the other layers as well...

Improve Car Dark layout colors, bring all layers up to date with Car Light, automate changes in all layers with script

---

README.md

Fix:readme:Fixed broken link #914

---

navit/icons/archaeological_site.svg
navit/icons/cave.svg
navit/textures/cemetery.svg
navit/textures/diagonal-stripes-gray.svg
navit/textures/diagonal-stripes.svg
navit/textures/quarry.svg
navit/textures/scrub.svg
navit/textures/wetland.svg
navit/textures/wood.svg

ändrad:        navit/icons/archaeological_site.svg
ändrad:        navit/icons/cave.svg
ändrad:        navit/textures/cemetery.svg
ändrad:        navit/textures/diagonal-stripes-gray.svg
ändrad:        navit/textures/diagonal-stripes.svg
ändrad:        navit/textures/quarry.svg
ändrad:        navit/textures/scrub.svg
ändrad:        navit/textures/wetland.svg
ändrad:        navit/textures/wood.svg
Thanks for contributing to Navit!
Before opening a pull request on navit, make sure your commit message follows our guidelines:
https://navit.readthedocs.io/en/trunk/development/commit_guidelines.html
and that your code is compliant with out coding style guidelines:
https://navit.readthedocs.io/en/trunk/development/programming_guidelines.html

added license information to fix #1048

---

gradle/wrapper/gradle-wrapper.properties

Just add the security check as mentioned in https://gitlab.com/fdroid/fdroiddata/-/issues/1843
see also #792

fix:build:android:Add extra security check for gradle.

---

navit/osd/core/osd_core.c

Thank you @JohnK-sljkrr  for providing this patch in #1036.  I cleaned up the patch. For some whitespaces I was not completely sure.

cleaned version of the patch by 1036

---

navit/item.h
navit/map.c
navit/map.h
navit/map/csv/csv.h
navit/mapset.c
navit/mapset.h
navit/route.c
navit/route_protected.h
navit/track.c

Some documentation improvements

Refactor:core:Documentation update

---

.circleci/config.yml

Fix:ci:Fix fdroidserver download path

---

navit/traffic.c

Found while investigating #1113, though it was not the cause of the issue

Fix:core:Fix read after free in traffic_message_restore_segments

---

docs/development/linux_development.rst

 Added minimum dependencies for Raspberry Pi OS

---

navit/item.c
navit/route.c
navit/traffic.c

Fix issues resulting in ignored traffic messages

---

navit/traffic.c

Currently, Navit attempts to recalculate delays per segment when restoring them from `traffic.xml`. This is both unnecessary (as the stored delay can be used for all purposes) and buggy (for some reason length calculations, which are used to distribute the total delay across segments, are inaccurate, and there are further issues when delays are bidirectional).
In short, simply taking the stored delay fixes any issues with delays changing when restoring items, and decreases the complexity of the code.

Fix:core:Do not recalculate delay when restoring traffic distortion items

---

navit/gui/gtk/destination.c

https://user-images.githubusercontent.com/5459286/133917125-0f5768fc-5577-486f-b8d2-959149c46aca.mov

GTKGUI -- Enable housenumbers in destination dialog

---

navit/vehicle/demo/vehicle_demo.c

If AF_UNDERGROUND flag is set in tracking attr_position_fix_type is 0. This enables for testing nightlayout for tunnels.
Configurable height value.
Deliver random values for speed, height, num_sats_used (vary around configured values).

Improvements for vehicle_demo

---

navit/graphics/qt5/QNavitQuick.cpp
navit/graphics/qt5/QNavitWidget.cpp
navit/graphics/svg_debug/graphics_svg_debug.c
navit/gui/qt5_qml/backend.cpp
navit/gui/qt5_qml/backend.h
navit/gui/qt5_qml/proxy.c
navit/gui/qt5_qml/qml_bookmark.cpp
navit/gui/qt5_qml/qml_poi.cpp
navit/navit.c
navit/vehicle/demo/vehicle_demo.c

Hi,
the compiler gives a lot of warnings during compilation. I tried to fix the most obvious ones. Feel free to cherry-pick whatever commit you seem fit.
Cheers,
Bastian

Fix some of the many compiler warning

---

navit/graphics.c
navit/graphics.h
navit/graphics/gtk_drawing_area/graphics_gtk_drawing_area.c

As discussed in #1194 we don't wanna carry complex code nobody uses

removed:graphics:Remove feature to read image from zip (See #1194)
